{
 "title": "default",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "var_fundings_ex",
    "label": "var_fundings_ex",
    "query": "SELECT DISTINCT ex\nFROM (\n  SELECT ex\n  FROM default.tickers\n  UNION ALL\n  SELECT ex\n  FROM default.fundings_curr_2025_01_12\n)"
   },
   {
    "name": "var_fundings_ccid",
    "label": "var_fundings_ccid",
    "query": "SELECT DISTINCT ccid\nFROM default.ex_k_to_ccid\nWHERE ccid != ''"
   },
   {
    "name": "contango_ex_vs_ex_ex_fut",
    "label": "contango_ex_vs_ex_ex_fut",
    "query": "bitget,bybit,gateio,kucoin,lbank,mexc"
   },
   {
    "name": "contango_ex_vs_ex_ex_spot",
    "label": "contango_ex_vs_ex_ex_spot",
    "query": "bitget,bybit,gateio,kucoin,lbank,mexc"
   },
   {
    "name": "contango_ex_vs_ex_ccid",
    "label": "contango_ex_vs_ex_ccid",
    "query": "SELECT ccid\nFROM default.ex_k_to_ccid_v2\nGROUP BY ccid"
   }
  ]
 },
 "panels": [
  {
   "title": "debug-must-be-zero",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "non-matched-tokens-with-ccid",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  t1.*,\n  conv_symbol_to_token_v2(t1.ex, t1.s) token_1,\n  t2.ccid\nFROM (\n  SELECT DISTINCT ex, s, k\n  FROM (\n    SELECT ex, s, k\n    FROM default.fundings_curr_2025_01_12\n    UNION ALL\n    SELECT ex, s, k\n    FROM default.tickers\n  )\n  WHERE (k = 'fut' AND ex != 'binance') OR (k = 'spot' AND ex = 'bybit')\n) t1\nLEFT JOIN (\n  SELECT *\n  FROM default.ex_k_to_ccid\n  WHERE k = 'fut'\n) t2\n  ON t1.ex = t2.ex AND token_1 = t2.base\nWHERE t2.ccid = ''\n  AND startsWith(notes, 'not-on-ui-on-') = 0\n  AND startsWith(notes, 'delisted-on-') = 0\n  AND startsWith(notes, 'index-fut-custom-for-ex-') = 0\nORDER BY ex, s",
       "rawQuery": "/* grafana dashboard=default, user=1 */\nSELECT\n  t1.*,\n  conv_symbol_to_token_v2(t1.ex, t1.s) token_1,\n  t2.ccid\nFROM (\n  SELECT DISTINCT ex, s, k\n  FROM (\n    SELECT ex, s, k\n    FROM default.fundings_curr_2025_01_12\n    UNION ALL\n    SELECT ex, s, k\n    FROM default.tickers\n  )\n  WHERE k = 'fut' AND ex != 'binance'\n) t1\nLEFT JOIN (\n  SELECT *\n  FROM default.ex_k_to_ccid\n  WHERE k = 'fut'\n) t2\n  ON t1.ex = t2.ex AND token_1 = t2.base\nWHERE t2.ccid = ''\n  AND startsWith(notes, 'not-on-ui-on-') = 0\n  AND startsWith(notes, 'delisted-on-') = 0\n  AND startsWith(notes, 'index-fut-custom-for-ex-') = 0\nORDER BY ex, s",
       "round": "0s"
      }
     ]
    },
    {
     "title": "duplicates-ccid",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT ex, base, count() AS amount\nFROM default.ex_k_to_ccid\nWHERE k = 'fut'\nGROUP BY ex, base\nHAVING amount != 1",
       "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT ex, base, count() AS amount\nFROM default.ex_k_to_ccid\nWHERE k = 'fut'\nGROUP BY ex, base\nHAVING amount != 1",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "debug-rest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "last-write-by-ex",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    ex,\n    max(ts_write) AS last_write\nFROM default.fundings_curr_2025_01_12\nWHERE toDate(ts_write) = today()\nGROUP BY ex\nORDER BY last_write ASC",
       "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT\n    ex,\n    max(ts_write) AS last_write\nFROM default.fundings_curr_2025_01_12\nWHERE toDate(ts_write) = today()\nGROUP BY ex\nORDER BY last_write ASC",
       "round": "0s"
      }
     ]
    },
    {
     "title": "non-on-ui-ccid",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 2 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT ex, base, notes\nFROM default.ex_k_to_ccid\nWHERE k = 'fut' AND startsWith(notes, 'not-on-ui-on-')",
       "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT ex, base, notes\nFROM default.ex_k_to_ccid\nWHERE k = 'fut' AND startsWith(notes, 'not-on-ui-on-')",
       "round": "0s"
      }
     ]
    },
    {
     "title": "parts-amount",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT count()\nFROM system.parts\nWHERE (database = 'default') AND (`table` = 'fundings_curr_2025_01_12')",
       "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT count()\nFROM system.parts\nWHERE (database = 'default') AND (`table` = 'fundings_curr_2025_01_12')",
       "round": "0s"
      }
     ]
    },
    {
     "title": "partitions-amount",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT count()\nFROM (\n  SELECT partition\n  FROM system.parts\n  WHERE (database = 'default') AND (`table` = 'fundings_curr_2025_01_12')\n  GROUP BY partition\n)",
       "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT count()\nFROM (\n  SELECT partition\n  FROM system.parts\n  WHERE (database = 'default') AND (`table` = 'fundings_curr_2025_01_12')\n  GROUP BY partition\n)",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "spreads-fut-perp-vs-spot (bitget, bybit, gateio, kucoin, mexc)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "contango-ex-vs-ex",
     "type": "table",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 3 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  ccid,\n  truncate((p_bid_fut - p_ask_spot) / p_ask_spot * 100, 2) diff_rel,\n  arrayElement(groupArrayIf(ex_link, k = 'fut'), 1) ex_link_fut,\n  arrayElement(groupArrayIf(ex_link, k = 'spot'), 1) ex_link_spot,\n  groupArrayIf(s, k = 'fut') s_fut,\n  groupArrayIf(s, k = 'spot') s_spot,\n  sum(if(k = 'fut', p_bid_per_1_token, 0)) p_bid_fut,\n  sum(if(k = 'spot', p_ask_per_1_token, 0)) p_ask_spot,\n  groupArrayIf(ts_write, k = 'fut') ts_write_fut,\n  groupArrayIf(ts_write, k = 'spot') ts_write_spot,\n  arrayElement(groupArrayIf(ex, k = 'fut'), 1) ex_fut,\n  arrayElement(groupArrayIf(ex, k = 'spot'), 1) ex_spot\nFROM (\n  SELECT\n    *,\n    row_number() OVER (PARTITION BY k, ccid ORDER BY p_bid_per_1_token DESC) as rank_lowest_bid,\n    row_number() OVER (PARTITION BY k, ccid ORDER BY p_ask_per_1_token ASC) as rank_highest_ask\n  FROM (\n    -- base-query start\n    SELECT\n      t1.*,\n      t2.ccid,\n      t2.notes,\n      t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n      t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n      -- row_number() OVER (PARTITION BY t1.ex, t1.k, t1.s ORDER BY t1.ts_write DESC) as rank_last_events_on_ex_by_s\n      row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n    FROM (\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n        CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n        toFloat64OrZero(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n        CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n          array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n        ) volumes,\n        CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n        CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'kucoin' AND _p_bid != 'null'\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.c') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        _p_bid _p_ask,\n        p_bid p_ask,\n        array(JSON_VALUE(obj_raw, '$.v')) volumes,\n        CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'lbank' AND _p_bid != ''\n      UNION ALL\n      SELECT\n        *,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n          array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n        ) volumes,\n        CONCAT(\n          if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n          if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n        ) ex_link\n      FROM default.tickers\n      WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n    ) t1\n    LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n    -- base-query end\n    WHERE ts_write >= NOW() - INTERVAL 10 MINUTES\n      AND t2.ccid != ''\n      AND startsWith(t2.notes, 'index-fut-') = 0\n      AND startsWith(t2.notes, 'non-fut-perp-') = 0\n      AND startsWith(t2.notes, 'non-usd-based-') = 0\n  )\n  WHERE rank_last_events_on_ex = 1\n)\nWHERE (k = 'fut' AND rank_lowest_bid = 1) OR (k = 'spot' AND rank_highest_ask = 1)\nGROUP BY ccid\nHAVING p_bid_fut != 0 AND p_ask_spot != 0\nORDER BY diff_rel DESC\nLIMIT 50",
       "rawQuery": "/* grafana dashboard=default, user=1 */\nSELECT\n  ccid,\n  truncate((p_bid_fut - p_ask_spot) / p_ask_spot * 100, 2) diff_rel,\n  arrayElement(groupArrayIf(ex_link, k = 'fut'), 1) ex_link_fut,\n  arrayElement(groupArrayIf(ex_link, k = 'spot'), 1) ex_link_spot,\n  groupArrayIf(s, k = 'fut') s_fut,\n  groupArrayIf(s, k = 'spot') s_spot,\n  sum(if(k = 'fut', p_bid_per_1_token, 0)) p_bid_fut,\n  sum(if(k = 'spot', p_ask_per_1_token, 0)) p_ask_spot,\n  groupArrayIf(ts_write, k = 'fut') ts_write_fut,\n  groupArrayIf(ts_write, k = 'spot') ts_write_spot,\n  arrayElement(groupArrayIf(ex, k = 'fut'), 1) ex_fut,\n  arrayElement(groupArrayIf(ex, k = 'spot'), 1) ex_spot\nFROM (\n  SELECT\n    *,\n    row_number() OVER (PARTITION BY k, ccid ORDER BY p_bid_per_1_token DESC) as rank_lowest_bid,\n    row_number() OVER (PARTITION BY k, ccid ORDER BY p_ask_per_1_token ASC) as rank_highest_ask\n  FROM (\n    \n    SELECT\n      t1.*,\n      t2.ccid,\n      t2.notes,\n      t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n      t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n      \n      row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n    FROM (\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n        CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n        toFloat64OrZero(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n        CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n          array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n        ) volumes,\n        CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n        CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'kucoin' AND _p_bid != 'null'\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.c') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        _p_bid _p_ask,\n        p_bid p_ask,\n        array(JSON_VALUE(obj_raw, '$.v')) volumes,\n        CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'lbank' AND _p_bid != ''\n      UNION ALL\n      SELECT\n        *,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n          array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n        ) volumes,\n        CONCAT(\n          if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n          if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n        ) ex_link\n      FROM default.tickers\n      WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n    ) t1\n    LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n    \n    WHERE ts_write >= NOW() - INTERVAL 10 MINUTES\n      AND t2.ccid != ''\n      AND startsWith(t2.notes, 'index-fut-') = 0\n      AND startsWith(t2.notes, 'non-fut-perp-') = 0\n      AND startsWith(t2.notes, 'non-usd-based-') = 0\n  )\n  WHERE rank_last_events_on_ex = 1\n)\nWHERE (k = 'fut' AND rank_lowest_bid = 1) OR (k = 'spot' AND rank_highest_ask = 1)\nGROUP BY ccid\nHAVING p_bid_fut != 0 AND p_ask_spot != 0\nORDER BY diff_rel DESC\nLIMIT 50",
       "round": "0s"
      }
     ]
    },
    {
     "title": "non-matched-ccids--must-be-0",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "-- NOTE: To check: 1. ignore pre-markets 2. ignore vol=0 3. look at contangos 4. look at backwardations\n-- XXX: because from time to time coingecko-api could return wrong identifiers =>\n--      check again added-by-jupy-busybox-coingecko-api-on-\nSELECT ex, k, s, volumes, notes\nFROM (\n  -- base-query start\n  SELECT\n    t1.*,\n    t2.ccid,\n    t2.notes,\n    t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n    t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n    row_number() OVER (PARTITION BY t1.ex, t1.k, t1.s ORDER BY t1.ts_write DESC) as rank_last_events_on_ex_by_s\n    -- row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n  FROM (\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n      CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n      toFloat64OrZero(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n      CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n        array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n      ) volumes,\n      CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n      CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'kucoin' AND _p_bid != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.c') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      _p_bid _p_ask,\n      p_bid p_ask,\n      array(JSON_VALUE(obj_raw, '$.v')) volumes,\n      CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'lbank' AND _p_bid != ''\n    UNION ALL\n    SELECT\n      *,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n        array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n      ) volumes,\n      CONCAT(\n        if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n        if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n      ) ex_link\n    FROM default.tickers\n    WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n  ) t1\n  LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n  -- base-query end\n  WHERE ts_write >= NOW() - INTERVAL 30 MINUTES\n    AND t2.ccid = ''\n    AND startsWith(t2.notes, 'index-fut-') = 0\n    AND startsWith(t2.notes, 'non-fut-perp-') = 0\n    AND startsWith(t2.notes, 'non-usd-based-') = 0\n    AND NOT (t2.notes LIKE 'not-found-on-coingecko-%' AND t2.notes LIKE '%not-found-in-other-exs-symbols-%')\n)\nWHERE rank_last_events_on_ex_by_s = 1\nORDER BY notes, ex, k",
       "rawQuery": "/* grafana dashboard=default, user=1 */\n\n\n\nSELECT ex, k, s, volumes, notes\nFROM (\n  \n  SELECT\n    t1.*,\n    t2.ccid,\n    t2.notes,\n    t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n    t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n    row_number() OVER (PARTITION BY t1.ex, t1.k, t1.s ORDER BY t1.ts_write DESC) as rank_last_events_on_ex_by_s\n    \n  FROM (\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n      CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n      toFloat64OrZero(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n      CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n        array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n      ) volumes,\n      CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n      CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'kucoin' AND _p_bid != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.c') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      _p_bid _p_ask,\n      p_bid p_ask,\n      array(JSON_VALUE(obj_raw, '$.v')) volumes,\n      CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'lbank' AND _p_bid != ''\n    UNION ALL\n    SELECT\n      *,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n        array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n      ) volumes,\n      CONCAT(\n        if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n        if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n      ) ex_link\n    FROM default.tickers\n    WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n  ) t1\n  LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n  \n  WHERE ts_write >= NOW() - INTERVAL 30 MINUTES\n    AND t2.ccid = ''\n    AND startsWith(t2.notes, 'index-fut-') = 0\n    AND startsWith(t2.notes, 'non-fut-perp-') = 0\n    AND startsWith(t2.notes, 'non-usd-based-') = 0\n    AND NOT (t2.notes LIKE 'not-found-on-coingecko-%' AND t2.notes LIKE '%not-found-in-other-exs-symbols-%')\n)\nWHERE rank_last_events_on_ex_by_s = 1\nORDER BY notes, ex, k",
       "round": "0s"
      }
     ]
    },
    {
     "title": "spread-ex-vs-ex-hist",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 9 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT t1.ts_write, (t2.p_fut / t1.p_spot - 1) * 100 spread_val\nFROM (\n  SELECT ccid, ts_write, p_bid_per_1_token p_spot\n  FROM (\n    -- base-query start\n    SELECT\n      t1.*,\n      t2.ccid,\n      t2.notes,\n      t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n      t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n      -- row_number() OVER (PARTITION BY t1.ex, t1.k, t1.s ORDER BY t1.ts_write DESC) as rank_last_events_on_ex_by_s\n      row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n    FROM (\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n        CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n        toFloat64OrZero(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n        CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n          array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n        ) volumes,\n        CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n        CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'kucoin' AND _p_bid != 'null'\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.c') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        _p_bid _p_ask,\n        p_bid p_ask,\n        array(JSON_VALUE(obj_raw, '$.v')) volumes,\n        CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'lbank' AND _p_bid != ''\n      UNION ALL\n      SELECT\n        *,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n          array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n        ) volumes,\n        CONCAT(\n          if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n          if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n        ) ex_link\n      FROM default.tickers\n      WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n    ) t1\n    LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n    -- base-query end\n    WHERE ts_write BETWEEN toDateTime($from) AND toDateTime($to)\n      AND t2.ccid != ''\n      AND startsWith(t2.notes, 'index-fut-') = 0\n      AND startsWith(t2.notes, 'non-fut-perp-') = 0\n      AND startsWith(t2.notes, 'non-usd-based-') = 0\n      AND k = 'spot'\n      AND ex = '$contango_ex_vs_ex_ex_spot'\n      AND ccid = '$contango_ex_vs_ex_ccid'\n  )\n) t1\nASOF LEFT JOIN (\n  SELECT ccid, ts_write, p_ask_per_1_token p_fut\n  FROM (\n    -- base-query start\n    SELECT\n      t1.*,\n      t2.ccid,\n      t2.notes,\n      t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n      t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n      -- row_number() OVER (PARTITION BY t1.ex, t1.k, t1.s ORDER BY t1.ts_write DESC) as rank_last_events_on_ex_by_s\n      row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n    FROM (\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n        CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n        toFloat64OrZero(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n        CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n          array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n        ) volumes,\n        CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n        CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'kucoin' AND _p_bid != 'null'\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.c') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        _p_bid _p_ask,\n        p_bid p_ask,\n        array(JSON_VALUE(obj_raw, '$.v')) volumes,\n        CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'lbank' AND _p_bid != ''\n      UNION ALL\n      SELECT\n        *,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n          array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n        ) volumes,\n        CONCAT(\n          if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n          if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n        ) ex_link\n      FROM default.tickers\n      WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n    ) t1\n    LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n    -- base-query end\n    WHERE ts_write BETWEEN toDateTime($from) AND toDateTime($to)\n      AND t2.ccid != ''\n      AND startsWith(t2.notes, 'index-fut-') = 0\n      AND startsWith(t2.notes, 'non-fut-perp-') = 0\n      AND startsWith(t2.notes, 'non-usd-based-') = 0\n      AND k = 'fut'\n      AND ex = '$contango_ex_vs_ex_ex_fut'\n      AND ccid = '$contango_ex_vs_ex_ccid'\n  )\n) t2\n  ON t1.ccid = t2.ccid AND t2.ts_write >= t1.ts_write\nWHERE p_fut != 0",
       "rawQuery": "/* grafana dashboard=default, user=1 */\nSELECT t1.ts_write, (t2.p_fut / t1.p_spot - 1) * 100 spread_val\nFROM (\n  SELECT ccid, ts_write, p_bid_per_1_token p_spot\n  FROM (\n    \n    SELECT\n      t1.*,\n      t2.ccid,\n      t2.notes,\n      t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n      t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n      \n      row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n    FROM (\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n        CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n        toFloat64OrZero(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n        CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n          array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n        ) volumes,\n        CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n        CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'kucoin' AND _p_bid != 'null'\n      UNION ALL\n      SELECT\n        *,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n          array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n        ) volumes,\n        CONCAT(\n          if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n          if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n        ) ex_link\n      FROM default.tickers t1\n      WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.c') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        _p_bid _p_ask,\n        p_bid p_ask,\n        array(JSON_VALUE(obj_raw, '$.v')) volumes,\n        CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'lbank' AND _p_bid != ''\n    ) t1\n    LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n    \n    WHERE ts_write BETWEEN toDateTime(1747141293) AND toDateTime(1747162893)\n      AND t2.ccid != ''\n      AND startsWith(t2.notes, 'index-fut-') = 0\n      AND startsWith(t2.notes, 'non-fut-perp-') = 0\n      AND startsWith(t2.notes, 'non-usd-based-') = 0\n      AND k = 'spot'\n      AND ex = 'lbank'\n      AND ccid = 'axelar'\n  )\n) t1\nASOF LEFT JOIN (\n  SELECT ccid, ts_write, p_ask_per_1_token p_fut\n  FROM (\n    \n    SELECT\n      t1.*,\n      t2.ccid,\n      t2.notes,\n      t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n      t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n      \n      row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n    FROM (\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n        CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n        toFloat64OrZero(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n        CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n          array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n        ) volumes,\n        CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n      UNION ALL\n      SELECT\n        *,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n        CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'kucoin' AND _p_bid != 'null'\n      UNION ALL\n      SELECT\n        *,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n        toFloat64(_p_bid) p_bid,\n        if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n        toFloat64(_p_ask) p_ask,\n        if(\n          k = 'fut',\n          array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n          array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n        ) volumes,\n        CONCAT(\n          if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n          if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n        ) ex_link\n      FROM default.tickers t1\n      WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n      UNION ALL\n      SELECT\n        *,\n        JSON_VALUE(obj_raw, '$.c') _p_bid,\n        toFloat64(_p_bid) p_bid,\n        _p_bid _p_ask,\n        p_bid p_ask,\n        array(JSON_VALUE(obj_raw, '$.v')) volumes,\n        CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n      FROM default.tickers\n      WHERE ex = 'lbank' AND _p_bid != ''\n    ) t1\n    LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n    \n    WHERE ts_write BETWEEN toDateTime(1747141293) AND toDateTime(1747162893)\n      AND t2.ccid != ''\n      AND startsWith(t2.notes, 'index-fut-') = 0\n      AND startsWith(t2.notes, 'non-fut-perp-') = 0\n      AND startsWith(t2.notes, 'non-usd-based-') = 0\n      AND k = 'fut'\n      AND ex = 'bitget'\n      AND ccid = 'axelar'\n  )\n) t2\n  ON t1.ccid = t2.ccid AND t2.ts_write >= t1.ts_write\nWHERE p_fut != 0",
       "round": "0s"
      },
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT t, 0 val FROM VALUES('t Datetime', (toDateTime($from)), (toDateTime($to)))",
       "rawQuery": "/* grafana dashboard=default, user=1 */\nSELECT t, 0 val FROM VALUES('t Datetime', (toDateTime(1747141293)), (toDateTime(1747162893)))",
       "round": "0s"
      }
     ]
    },
    {
     "title": "assert-match-token-price-ccid--must-be-0",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 9 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "-- NOTE: assert-match - most probably the same symbols pairs with +-10% the same price have the same ccid\nSELECT\n  conv_symbol_to_token_v2(ex, s) token,\n  truncate((max(p_bid_per_1_token) - min(p_bid_per_1_token)) / min(p_bid_per_1_token) * 100, 4) p_bids_diff_rel,\n  groupUniqArray(ccid) ccids,\n  groupArray(p_bid_per_1_token) p_bids\nFROM (\n  -- base-query start\n  SELECT\n    t1.*,\n    t2.ccid,\n    t2.notes,\n    t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n    t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n    -- row_number() OVER (PARTITION BY t1.ex, t1.k, t1.s ORDER BY t1.ts_write DESC) as rank_last_events_on_ex_by_s\n    row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n  FROM (\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n      CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n      toFloat64OrZero(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n      CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n        array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n      ) volumes,\n      CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n      CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'kucoin' AND _p_bid != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.c') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      _p_bid _p_ask,\n      p_bid p_ask,\n      array(JSON_VALUE(obj_raw, '$.v')) volumes,\n      CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'lbank' AND _p_bid != ''\n    UNION ALL\n    SELECT\n      *,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n        array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n      ) volumes,\n      CONCAT(\n        if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n        if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n      ) ex_link\n    FROM default.tickers\n    WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n  ) t1\n  LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n  -- base-query end\n  WHERE ts_write >= NOW() - INTERVAL 10 MINUTES\n    AND t2.ccid != ''\n    AND startsWith(t2.notes, 'index-fut-') = 0\n    AND startsWith(t2.notes, 'non-fut-perp-') = 0\n    AND startsWith(t2.notes, 'non-usd-based-') = 0\n)\nWHERE rank_last_events_on_ex = 1\nGROUP BY token\nHAVING p_bids_diff_rel < 10 AND length(ccids) != 1",
       "rawQuery": "/* grafana dashboard=default, user=1 */\n\nSELECT\n  conv_symbol_to_token_v2(ex, s) token,\n  truncate((max(p_bid_per_1_token) - min(p_bid_per_1_token)) / min(p_bid_per_1_token) * 100, 4) p_bids_diff_rel,\n  groupUniqArray(ccid) ccids,\n  groupArray(p_bid_per_1_token) p_bids\nFROM (\n  \n  SELECT\n    t1.*,\n    t2.ccid,\n    t2.notes,\n    t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n    t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n    \n    row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n  FROM (\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n      CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n      toFloat64OrZero(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n      CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n        array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n      ) volumes,\n      CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n      CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'kucoin' AND _p_bid != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.c') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      _p_bid _p_ask,\n      p_bid p_ask,\n      array(JSON_VALUE(obj_raw, '$.v')) volumes,\n      CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'lbank' AND _p_bid != ''\n    UNION ALL\n    SELECT\n      *,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n        array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n      ) volumes,\n      CONCAT(\n        if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n        if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n      ) ex_link\n    FROM default.tickers\n    WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n  ) t1\n  LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n  \n  WHERE ts_write >= NOW() - INTERVAL 10 MINUTES\n    AND t2.ccid != ''\n    AND startsWith(t2.notes, 'index-fut-') = 0\n    AND startsWith(t2.notes, 'non-fut-perp-') = 0\n    AND startsWith(t2.notes, 'non-usd-based-') = 0\n)\nWHERE rank_last_events_on_ex = 1\nGROUP BY token\nHAVING p_bids_diff_rel < 10 AND length(ccids) != 1",
       "round": "0s"
      }
     ]
    },
    {
     "title": "fut-spot-ex-vs-ex-hist",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 15 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT ts_write, p_ask_per_1_token p_fut\nFROM (\n  -- base-query start\n  SELECT\n    t1.*,\n    t2.ccid,\n    t2.notes,\n    t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n    t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n    -- row_number() OVER (PARTITION BY t1.ex, t1.k, t1.s ORDER BY t1.ts_write DESC) as rank_last_events_on_ex_by_s\n    row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n  FROM (\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n      CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n      toFloat64OrZero(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n      CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n        array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n      ) volumes,\n      CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n      CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'kucoin' AND _p_bid != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.c') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      _p_bid _p_ask,\n      p_bid p_ask,\n      array(JSON_VALUE(obj_raw, '$.v')) volumes,\n      CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'lbank' AND _p_bid != ''\n    UNION ALL\n    SELECT\n      *,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n        array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n      ) volumes,\n      CONCAT(\n        if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n        if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n      ) ex_link\n    FROM default.tickers\n    WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n  ) t1\n  LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n  -- base-query end\n  WHERE ts_write BETWEEN toDateTime($from) AND toDateTime($to)\n    AND t2.ccid != ''\n    AND startsWith(t2.notes, 'index-fut-') = 0\n    AND startsWith(t2.notes, 'non-fut-perp-') = 0\n    AND startsWith(t2.notes, 'non-usd-based-') = 0\n    AND k = 'fut'\n    AND ex = '$contango_ex_vs_ex_ex_fut'\n    AND ccid = '$contango_ex_vs_ex_ccid'\n)",
       "rawQuery": "/* grafana dashboard=default, user=1 */\nSELECT ts_write, p_ask_per_1_token p_fut\nFROM (\n  \n  SELECT\n    t1.*,\n    t2.ccid,\n    t2.notes,\n    t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n    t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n    \n    row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n  FROM (\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n      CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n      toFloat64OrZero(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n      CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n        array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n      ) volumes,\n      CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n      CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'kucoin' AND _p_bid != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.c') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      _p_bid _p_ask,\n      p_bid p_ask,\n      array(JSON_VALUE(obj_raw, '$.v')) volumes,\n      CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'lbank' AND _p_bid != ''\n    UNION ALL\n    SELECT\n      *,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n        array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n      ) volumes,\n      CONCAT(\n        if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n        if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n      ) ex_link\n    FROM default.tickers\n    WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n  ) t1\n  LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n  \n  WHERE ts_write BETWEEN toDateTime(1747141455) AND toDateTime(1747163055)\n    AND t2.ccid != ''\n    AND startsWith(t2.notes, 'index-fut-') = 0\n    AND startsWith(t2.notes, 'non-fut-perp-') = 0\n    AND startsWith(t2.notes, 'non-usd-based-') = 0\n    AND k = 'fut'\n    AND ex = 'bitget'\n    AND ccid = 'axelar'\n)\nUNION ALL\nSELECT ts_write, p_ask_per_1_token p_spot\nFROM (\n  \n  SELECT\n    t1.*,\n    t2.ccid,\n    t2.notes,\n    t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n    t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n    \n    row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n  FROM (\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n      CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n      toFloat64OrZero(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n      CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n        array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n      ) volumes,\n      CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n      CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'kucoin' AND _p_bid != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.c') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      _p_bid _p_ask,\n      p_bid p_ask,\n      array(JSON_VALUE(obj_raw, '$.v')) volumes,\n      CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'lbank' AND _p_bid != ''\n    UNION ALL\n    SELECT\n      *,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n        array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n      ) volumes,\n      CONCAT(\n        if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n        if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n      ) ex_link\n    FROM default.tickers\n    WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n  ) t1\n  LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n  \n  WHERE ts_write BETWEEN toDateTime(1747141455) AND toDateTime(1747163055)\n    AND t2.ccid != ''\n    AND startsWith(t2.notes, 'index-fut-') = 0\n    AND startsWith(t2.notes, 'non-fut-perp-') = 0\n    AND startsWith(t2.notes, 'non-usd-based-') = 0\n    AND k = 'spot'\n    AND ex = 'lbank'\n    AND ccid = 'axelar'\n)",
       "round": "0s"
      },
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT ts_write, p_bid_per_1_token p_spot\nFROM (\n  -- base-query start\n  SELECT\n    t1.*,\n    t2.ccid,\n    t2.notes,\n    t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n    t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n    -- row_number() OVER (PARTITION BY t1.ex, t1.k, t1.s ORDER BY t1.ts_write DESC) as rank_last_events_on_ex_by_s\n    row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n  FROM (\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n      CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n      toFloat64OrZero(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n      CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n        array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n      ) volumes,\n      CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n      CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'kucoin' AND _p_bid != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.c') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      _p_bid _p_ask,\n      p_bid p_ask,\n      array(JSON_VALUE(obj_raw, '$.v')) volumes,\n      CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'lbank' AND _p_bid != ''\n    UNION ALL\n    SELECT\n      *,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      if(\n        k = 'fut',\n        array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n        array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n      ) volumes,\n      CONCAT(\n        if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n        if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n      ) ex_link\n    FROM default.tickers\n    WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n  ) t1\n  LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n  -- base-query end\n  WHERE ts_write BETWEEN toDateTime($from) AND toDateTime($to)\n    AND t2.ccid != ''\n    AND startsWith(t2.notes, 'index-fut-') = 0\n    AND startsWith(t2.notes, 'non-fut-perp-') = 0\n    AND startsWith(t2.notes, 'non-usd-based-') = 0\n    AND k = 'spot'\n    AND ex = '$contango_ex_vs_ex_ex_spot'\n    AND ccid = '$contango_ex_vs_ex_ccid'\n)",
       "rawQuery": "/* grafana dashboard=default, user=1 */\nSELECT ts_write, p_bid_per_1_token p_spot\nFROM (\n  \n  SELECT\n    t1.*,\n    t2.ccid,\n    t1.p_bid / pow(10, t2.qty_mult) p_bid_per_1_token,\n    t1.p_ask / pow(10, t2.qty_mult) p_ask_per_1_token,\n    row_number() OVER (PARTITION BY t1.ex, t1.k, t2.ccid ORDER BY t1.ts_write DESC) as rank_last_events_on_ex\n  FROM (\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n      toFloat64OrZero(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n    UNION ALL\n    SELECT\n      *,\n      JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n      toFloat64(_p_bid) p_bid,\n      JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n      toFloat64(_p_ask) p_ask,\n      CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'gateio' AND _p_bid != ''\n    UNION ALL\n    SELECT\n      *,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      CONCAT(if(k = 'fut', 'https://kucoin.com/futures/trade/', 'https://kucoin.com/trade/margin/'), s) ex_link\n    FROM default.tickers\n    WHERE ex = 'kucoin' AND _p_bid != 'null'\n    UNION ALL\n    SELECT\n      *,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n      toFloat64(_p_bid) p_bid,\n      if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n      toFloat64(_p_ask) p_ask,\n      CONCAT(\n        if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n        if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n      ) ex_link\n    FROM default.tickers t1\n    WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n  ) t1\n  LEFT JOIN default.ex_k_to_ccid_v2 t2 USING (ex, k, s)\n  WHERE ts_write BETWEEN toDateTime(1747142454) AND toDateTime(1747164054)\n    AND t2.ccid != ''\n    AND startsWith(t2.notes, 'index-fut-') = 0\n    AND startsWith(t2.notes, 'non-fut-perp-') = 0\n    AND startsWith(t2.notes, 'non-usd-based-') = 0\n  \n    AND k = 'spot'\n    AND ex = 'gateio'\n    AND ccid = 'constitutiondao'\n  \n)",
       "round": "0s"
      }
     ]
    },
    {
     "title": "assert-match-base-quote-ccid--must-be-0",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 15 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "-- NOTE: assert-match - most probably identical symbols pairs have the same ccid\nSELECT\n  base,\n  quote,\n  groupUniqArray(ccid) ccids,\n  arraySum(arrayMap(s -> s like '%assert-match-checked-for-token-ccid-diff%', groupUniqArray(notes))) == count() is_all_already_checked\nFROM default.ex_k_to_ccid_v2\nWHERE quote in ('USDE', 'WUSD', 'TUSD', 'USDT', 'USDQ', 'DAI', 'USDR', 'USDC')\n  AND startsWith(notes, 'index-fut-') = 0\n  AND startsWith(notes, 'non-fut-perp-') = 0\n  AND startsWith(notes, 'non-usd-based-') = 0\nGROUP BY base, quote\nHAVING length(ccids) != 1 AND is_all_already_checked = 0",
       "rawQuery": "/* grafana dashboard=default, user=1 */\n\nSELECT\n  base,\n  quote,\n  groupUniqArray(ccid) ccids,\n  arraySum(arrayMap(s -> s like '%assert-match-checked-for-token-ccid-diff%', groupUniqArray(notes))) == count() is_all_already_checked\nFROM default.ex_k_to_ccid_v2\nWHERE quote in ('USDE', 'WUSD', 'TUSD', 'USDT', 'USDQ', 'DAI', 'USDR', 'USDC')\n  AND startsWith(notes, 'index-fut-') = 0\n  AND startsWith(notes, 'non-fut-perp-') = 0\n  AND startsWith(notes, 'non-usd-based-') = 0\nGROUP BY base, quote\nHAVING length(ccids) != 1 AND is_all_already_checked = 0",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "spreads-fut-perp-vs-spot-on-base-token (bitget, bybit, gateio, kucoin, lbank, mexc)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "contango-ex-vs-ex-on-base-token",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 4 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "-- TODO: for huge spread symbols either ignore them (code below) or make external mapping\nSELECT\n  `token.1`,\n  truncate((p_bid_fut - p_ask_spot) / p_ask_spot * 100, 2) diff_rel,\n  arrayElement(groupArrayIf(ex_link, k = 'fut'), 1) ex_link_fut,\n  arrayElement(groupArrayIf(ex_link, k = 'spot'), 1) ex_link_spot,\n  groupArrayIf(s, k = 'fut') s_fut,\n  groupArrayIf(s, k = 'spot') s_spot,\n  sum(if(k = 'fut', p_bid_per_1_token, 0)) p_bid_fut,\n  sum(if(k = 'spot', p_ask_per_1_token, 0)) p_ask_spot,\n  groupArrayIf(ts_write, k = 'fut') ts_write_fut,\n  groupArrayIf(ts_write, k = 'spot') ts_write_spot,\n  arrayElement(groupArrayIf(ex, k = 'fut'), 1) ex_fut,\n  arrayElement(groupArrayIf(ex, k = 'spot'), 1) ex_spot\nFROM (\n  SELECT\n    t1.*,\n    row_number() OVER (PARTITION BY t1.k, t1.`token.1` ORDER BY t1.p_bid_per_1_token DESC) as rank_lowest_bid,\n    row_number() OVER (PARTITION BY t1.k, t1.`token.1` ORDER BY t1.p_ask_per_1_token ASC) as rank_highest_ask\n  FROM (\n    SELECT\n      *,\n      p_bid / pow(10, `token.3`) p_bid_per_1_token,\n      p_ask / pow(10, `token.3`) p_ask_per_1_token,\n      row_number() OVER (PARTITION BY ex, k, `token.1` ORDER BY ts_write DESC) as rank_last_events_on_ex\n    FROM (\n      SELECT *, untuple(ext_tokens_meta_v3(ex, k, s)) AS token\n      FROM (\n        SELECT\n          *,\n          JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n          toFloat64(_p_bid) p_bid,\n          JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n          toFloat64(_p_ask) p_ask,\n          array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n          CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n        FROM default.tickers\n        WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n        UNION ALL\n        SELECT\n          *,\n          JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n          toFloat64OrZero(_p_bid) p_bid,\n          JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n          toFloat64(_p_ask) p_ask,\n          array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n          CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n        FROM default.tickers\n        WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n        UNION ALL\n        SELECT\n          *,\n          JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n          toFloat64(_p_bid) p_bid,\n          JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n          toFloat64(_p_ask) p_ask,\n          if(\n            k = 'fut',\n            array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n            array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n          ) volumes,\n          CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n        FROM default.tickers\n        WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n        UNION ALL\n        SELECT\n          *,\n          if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n          toFloat64(_p_bid) p_bid,\n          if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n          toFloat64(_p_ask) p_ask,\n          if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n          CONCAT(if(k = 'fut', 'https://www.kucoin.com/futures/trade/', 'https://www.kucoin.com/trade/margin/'), s) ex_link\n        FROM default.tickers\n        WHERE ex = 'kucoin' AND _p_bid != 'null'\n        UNION ALL\n        SELECT\n          *,\n          JSON_VALUE(obj_raw, '$.c') _p_bid,\n          toFloat64(_p_bid) p_bid,\n          _p_bid _p_ask,\n          p_bid p_ask,\n          array(JSON_VALUE(obj_raw, '$.v')) volumes,\n          CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n        FROM default.tickers\n        WHERE ex = 'lbank' AND _p_bid != ''\n        UNION ALL\n        SELECT\n          *,\n          if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n          toFloat64(_p_bid) p_bid,\n          if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n          toFloat64(_p_ask) p_ask,\n          if(\n            k = 'fut',\n            array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n            array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n          ) volumes,\n          CONCAT(\n            if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n            if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n          ) ex_link\n        FROM default.tickers\n        WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n      )\n      WHERE ts_write >= NOW() - INTERVAL 10 MINUTES\n    )\n    WHERE `token.2` in ('USDE', 'USDT', 'USDQ', 'DAI', 'USDR', 'USDC')\n  ) t1\n  LEFT JOIN (\n    SELECT *\n    FROM VALUES(\n      'ex String, k String, s String, ignore UInt8',\n      ('gateio', 'spot', 'GTC_USDT', 1),\n      ('gateio', 'spot', 'MTN_USDT', 1),\n      ('gateio', 'spot', 'TALK_USDT', 1),\n      ('gateio', 'spot', 'CULT_USDT', 1),\n      ('gateio', 'spot', 'QI_USDT', 1),\n      ('kucoin', 'fut', 'XBTUSDCM', 1),\n      ('kucoin', 'fut', 'XBTUSDTM', 1),\n      ('kucoin', 'fut', 'NEIROUSDTM', 1),\n      ('kucoin', 'spot', 'FORM-USDT', 1),\n      ('kucoin', 'spot', 'ACE-USDT', 1),\n      ('kucoin', 'spot', 'LAYER-USDT', 1),\n      ('kucoin', 'spot', 'ARC-USDT', 1),\n      ('kucoin', 'spot', 'BROCCOLI-USDT', 1),\n      ('lbank', 'fut', 'TROLLUSDT', 1),\n      ('lbank', 'fut', 'TSTUSDT', 1),\n      ('lbank', 'fut', 'VELOUSDT', 1),\n      ('lbank', 'spot', 'aic_usdt', 1),\n      ('lbank', 'spot', 'mnt_usdt', 1),\n      ('lbank', 'spot', 'send_usdt', 1),\n      ('lbank', 'spot', 'neiro_usdt', 1),\n      ('lbank', 'spot', 'super_usdt', 1),\n      ('lbank', 'spot', 'pundix_usdt', 1),\n      ('lbank', 'spot', 'sc_usdt', 1),\n      ('mexc', 'spot', 'MAGAUSDT', 1),\n      ('mexc', 'spot', 'ARCUSDT', 1),\n      ('mexc', 'spot', 'ALTUSDT', 1),\n      ('mexc', 'spot', 'QIUSDT', 1)\n    )\n  ) t2\n    USING (ex, k, s)\n  WHERE rank_last_events_on_ex = 1\n    AND t2.ignore = 0\n)\nWHERE (k = 'fut' AND rank_lowest_bid = 1) OR (k = 'spot' AND rank_highest_ask = 1)\nGROUP BY `token.1`\nHAVING p_bid_fut != 0 AND p_ask_spot != 0\nORDER BY diff_rel DESC\nLIMIT 100",
     "rawQuery": "/* grafana dashboard=default, user=1 */\n\nSELECT\n  `token.1`,\n  truncate((p_bid_fut - p_ask_spot) / p_ask_spot * 100, 2) diff_rel,\n  arrayElement(groupArrayIf(ex_link, k = 'fut'), 1) ex_link_fut,\n  arrayElement(groupArrayIf(ex_link, k = 'spot'), 1) ex_link_spot,\n  groupArrayIf(s, k = 'fut') s_fut,\n  groupArrayIf(s, k = 'spot') s_spot,\n  sum(if(k = 'fut', p_bid_per_1_token, 0)) p_bid_fut,\n  sum(if(k = 'spot', p_ask_per_1_token, 0)) p_ask_spot,\n  groupArrayIf(ts_write, k = 'fut') ts_write_fut,\n  groupArrayIf(ts_write, k = 'spot') ts_write_spot,\n  arrayElement(groupArrayIf(ex, k = 'fut'), 1) ex_fut,\n  arrayElement(groupArrayIf(ex, k = 'spot'), 1) ex_spot\nFROM (\n  SELECT\n    t1.*,\n    row_number() OVER (PARTITION BY t1.k, t1.`token.1` ORDER BY t1.p_bid_per_1_token DESC) as rank_lowest_bid,\n    row_number() OVER (PARTITION BY t1.k, t1.`token.1` ORDER BY t1.p_ask_per_1_token ASC) as rank_highest_ask\n  FROM (\n    SELECT\n      *,\n      p_bid / pow(10, `token.3`) p_bid_per_1_token,\n      p_ask / pow(10, `token.3`) p_ask_per_1_token,\n      row_number() OVER (PARTITION BY ex, k, `token.1` ORDER BY ts_write DESC) as rank_last_events_on_ex\n    FROM (\n      SELECT *, untuple(ext_tokens_meta_v3(ex, k, s)) AS token\n      FROM (\n        SELECT\n          *,\n          JSON_VALUE(obj_raw, '$.bidPr') _p_bid,\n          toFloat64(_p_bid) p_bid,\n          JSON_VALUE(obj_raw, '$.askPr') _p_ask,\n          toFloat64(_p_ask) p_ask,\n          array(JSON_VALUE(obj_raw, '$.baseVolume'), JSON_VALUE(obj_raw, '$.quoteVolume')) volumes,\n          CONCAT(if(k = 'fut', 'https://bitget.com/futures/usdt/', 'https://bitget.com/spot/'), s) ex_link\n        FROM default.tickers\n        WHERE ex = 'bitget' AND _p_bid != 'null' AND _p_ask != 'null'\n        UNION ALL\n        SELECT\n          *,\n          JSON_VALUE(obj_raw, '$.bid1Price') _p_bid,\n          toFloat64OrZero(_p_bid) p_bid,\n          JSON_VALUE(obj_raw, '$.ask1Price') _p_ask,\n          toFloat64(_p_ask) p_ask,\n          array(JSON_VALUE(obj_raw, '$.volume24h')) volumes,\n          CONCAT(if(k = 'fut', 'https://bybit.com/trade/usdt/', 'https://bybit.com/en/trade/spot/'), s) ex_link\n        FROM default.tickers\n        WHERE ex = 'bybit' AND _p_bid != '' AND _p_ask != ''\n        UNION ALL\n        SELECT\n          *,\n          JSON_VALUE(obj_raw, '$.highest_bid') _p_bid,\n          toFloat64(_p_bid) p_bid,\n          JSON_VALUE(obj_raw, '$.lowest_ask') _p_ask,\n          toFloat64(_p_ask) p_ask,\n          if(\n            k = 'fut',\n            array(JSON_VALUE(obj_raw, '$.volume_24h_base'), JSON_VALUE(obj_raw, '$.volume_24h_quote')),\n            array(JSON_VALUE(obj_raw, '$.base_volume'), JSON_VALUE(obj_raw, '$.quote_volume'))\n          ) volumes,\n          CONCAT(if(k = 'fut', 'https://gate.io/futures/USDT/', 'https://gate.io/trade/'), s) ex_link\n        FROM default.tickers\n        WHERE ex = 'gateio' AND _p_bid != '' AND _p_ask != ''\n        UNION ALL\n        SELECT\n          *,\n          if(k = 'fut', JSON_VALUE(obj_raw, '$.bestBidPrice'), JSON_VALUE(obj_raw, '$.buy')) _p_bid,\n          toFloat64(_p_bid) p_bid,\n          if(k = 'fut', JSON_VALUE(obj_raw, '$.bestAskPrice'), JSON_VALUE(obj_raw, '$.sell')) _p_ask,\n          toFloat64(_p_ask) p_ask,\n          if(k = 'fut', array(), array(JSON_VALUE(obj_raw, '$.vol'), JSON_VALUE(obj_raw, '$.volValue'))) volumes,\n          CONCAT(if(k = 'fut', 'https://www.kucoin.com/futures/trade/', 'https://www.kucoin.com/trade/margin/'), s) ex_link\n        FROM default.tickers\n        WHERE ex = 'kucoin' AND _p_bid != 'null'\n        UNION ALL\n        SELECT\n          *,\n          JSON_VALUE(obj_raw, '$.c') _p_bid,\n          toFloat64(_p_bid) p_bid,\n          _p_bid _p_ask,\n          p_bid p_ask,\n          array(JSON_VALUE(obj_raw, '$.v')) volumes,\n          CONCAT(if(k = 'fut', 'https://lbank.com/futures/', 'https://lbank.com/trade/'), s) ex_link\n        FROM default.tickers\n        WHERE ex = 'lbank' AND _p_bid != ''\n        UNION ALL\n        SELECT\n          *,\n          if (k = 'fut', JSON_VALUE(obj_raw, '$.bid1'), JSON_VALUE(obj_raw, '$.bidPrice')) _p_bid,\n          toFloat64(_p_bid) p_bid,\n          if (k = 'fut', JSON_VALUE(obj_raw, '$.ask1'), JSON_VALUE(obj_raw, '$.askPrice')) _p_ask,\n          toFloat64(_p_ask) p_ask,\n          if(\n            k = 'fut',\n            array(JSON_VALUE(obj_raw, '$.volume24'), JSON_VALUE(obj_raw, '$.holdVol')),\n            array(JSON_VALUE(obj_raw, '$.volume'), JSON_VALUE(obj_raw, '$.quoteVolume'))\n          ) volumes,\n          CONCAT(\n            if(k = 'fut', 'https://mexc.com/futures/', 'https://mexc.com/exchange/'),\n            if (k = 'fut', s, replaceRegexpOne(s, 'USDT$', '_USDT'))\n          ) ex_link\n        FROM default.tickers\n        WHERE ex = 'mexc' AND k = 'spot' AND _p_bid != ''\n      )\n      WHERE ts_write >= NOW() - INTERVAL 10 MINUTES\n    )\n    WHERE `token.2` in ('USDE', 'USDT', 'USDQ', 'DAI', 'USDR', 'USDC')\n  ) t1\n  LEFT JOIN (\n    SELECT *\n    FROM VALUES(\n      'ex String, k String, s String, ignore UInt8',\n      ('gateio', 'spot', 'GTC_USDT', 1),\n      ('gateio', 'spot', 'MTN_USDT', 1),\n      ('gateio', 'spot', 'TALK_USDT', 1),\n      ('gateio', 'spot', 'CULT_USDT', 1),\n      ('gateio', 'spot', 'QI_USDT', 1),\n      ('kucoin', 'fut', 'XBTUSDCM', 1),\n      ('kucoin', 'fut', 'XBTUSDTM', 1),\n      ('kucoin', 'fut', 'NEIROUSDTM', 1),\n      ('kucoin', 'spot', 'FORM-USDT', 1),\n      ('kucoin', 'spot', 'ACE-USDT', 1),\n      ('kucoin', 'spot', 'LAYER-USDT', 1),\n      ('kucoin', 'spot', 'ARC-USDT', 1),\n      ('kucoin', 'spot', 'BROCCOLI-USDT', 1),\n      ('lbank', 'fut', 'TROLLUSDT', 1),\n      ('lbank', 'fut', 'TSTUSDT', 1),\n      ('lbank', 'fut', 'VELOUSDT', 1),\n      ('lbank', 'spot', 'aic_usdt', 1),\n      ('lbank', 'spot', 'mnt_usdt', 1),\n      ('lbank', 'spot', 'send_usdt', 1),\n      ('lbank', 'spot', 'neiro_usdt', 1),\n      ('lbank', 'spot', 'super_usdt', 1),\n      ('lbank', 'spot', 'pundix_usdt', 1),\n      ('lbank', 'spot', 's_usdt', 1),\n      ('mexc', 'spot', 'MAGAUSDT', 1),\n      ('mexc', 'spot', 'ARCUSDT', 1),\n      ('mexc', 'spot', 'ALTUSDT', 1),\n      ('mexc', 'spot', 'QIUSDT', 1)\n    )\n  ) t2\n    USING (ex, k, s)\n  WHERE rank_last_events_on_ex = 1\n    AND t2.ignore = 0\n)\nWHERE (k = 'fut' AND rank_lowest_bid = 1) OR (k = 'spot' AND rank_highest_ask = 1)\nGROUP BY `token.1`\nHAVING p_bid_fut != 0 AND p_ask_spot != 0\nORDER BY diff_rel DESC\nLIMIT 100",
     "round": "0s"
    }
   ]
  },
  {
   "title": "TODO: [ext_tokens_meta_v3] show what's not extracted",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "contextWindowSize": "10",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=default, user=1 */\nSELECT (intDiv(toUInt32(undefined), 30) * 30) * 1000 as t, count() FROM undefined WHERE undefined >= toDateTime(1747554721) AND undefined <= toDateTime(1747576321) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "TODO: [ext_tokens_meta_v3] show what has huge spread",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "contextWindowSize": "10",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=default, user=1 */\nSELECT (intDiv(toUInt32(undefined), 30) * 30) * 1000 as t, count() FROM undefined WHERE undefined >= toDateTime(1747554756) AND undefined <= toDateTime(1747576356) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "TODO: [ext_tokens_meta_v3] show what has single symbol",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "contextWindowSize": "10",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=default, user=1 */\nSELECT (intDiv(toUInt32(undefined), 30) * 30) * 1000 as t, count() FROM undefined WHERE undefined >= toDateTime(1747554756) AND undefined <= toDateTime(1747576356) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "fundings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "fundings-curr",
     "type": "table",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 159 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT * EXCEPT (rank_out, _fund_1h_min, _fund_1h_max)\nFROM (\n    SELECT\n        ccid,\n        truncate(_fund_1h_max - _fund_1h_min, 6) diff_abs_1h,\n        truncate(_fund_1h_max * 8 - _fund_1h_min * 8, 6) diff_abs_8h,\n        first_value(ex) OVER w_asc AS ex_min,\n        first_value(ex) OVER w_desc AS ex_max,\n        first_value(ts) OVER w_asc AS ts_min,\n        first_value(ts) OVER w_desc AS ts_max,\n        token_1,\n        first_value(funding_rate_1h) OVER w_asc AS _fund_1h_min,\n        first_value(funding_rate_1h) OVER w_desc AS _fund_1h_max,\n        truncate(_fund_1h_min, 6) fund_1h_min,\n        truncate(_fund_1h_max, 6) fund_1h_max,\n        truncate(_fund_1h_min * 8, 6) fund_8h_min,\n        truncate(_fund_1h_max * 8, 6) fund_8h_max,\n        row_number() OVER (PARTITION BY ccid) rank_out\n    FROM (\n        SELECT * EXCEPT (rank)\n        FROM (\n            SELECT\n                t1.ex,\n                conv_symbol_to_token_v2(t1.ex, s) token_1,\n                t1.funding_rate / t1.funding_hours funding_rate_1h,\n                row_number() OVER (PARTITION BY ex, s ORDER BY ts DESC) AS rank,\n                t2.ccid,\n                toDateTime(t1.ts / 1000) ts\n            FROM (\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, toUInt64(t2.funding_interval / 60) funding_hours\n                    FROM (\n                        SELECT *\n                        FROM default.tickers\n                        WHERE ex = 'bybit' AND k = 'fut'\n                    ) t1\n                    INNER JOIN (\n                        SELECT s, funding_interval\n                        FROM default.bybit_instruments_info\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, funding_hours\n                    FROM (\n                        SELECT *\n                        FROM default.tickers\n                        WHERE ex = 'gateio' AND k = 'fut'\n                    ) t1\n                    INNER JOIN (\n                        SELECT s, toUInt64(JSONExtract(contract_raw, 'funding_interval', 'UInt64') / 60 / 60) funding_hours\n                        FROM default.gateio_contracts\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'hyperliquid'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'arkm'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, funding_interval funding_hours\n                    FROM (\n                        SELECT *\n                        FROM default.fundings_curr_2025_01_12\n                        WHERE ex = 'paradex'\n                    ) t1\n                    INNER JOIN (\n                        SELECT s, funding_interval\n                        FROM default.paradex_markets\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate / 10e17 funding_rate, ts * 1000 ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'polynomial-fi'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.tickers\n                    WHERE ex = 'apex-pro'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.tickers\n                    WHERE ex = 'apex-omni'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'aevo'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate, ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'bitunix'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'coinex'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'bingx'\n                )\n            ) t1\n            INNER JOIN (\n                SELECT *\n                FROM default.ex_k_to_ccid\n                WHERE k = 'fut'\n            ) t2\n                ON t1.ex = t2.ex AND token_1 = t2.base\n            WHERE t2.ccid != ''\n                AND startsWith(notes, 'not-on-ui-on-') = 0\n                AND startsWith(notes, 'delisted-on-') = 0\n                AND startsWith(notes, 'index-fut-custom-for-ex-') = 0\n                AND ts_write >= NOW() - INTERVAL 30 MINUTE\n        )\n        WHERE rank = 1\n    )\n    WINDOW w_asc AS (PARTITION BY ccid ORDER BY funding_rate_1h ASC),\n        w_desc AS (PARTITION BY ccid ORDER BY funding_rate_1h DESC)\n)\nWHERE rank_out = 1\nORDER BY abs(diff_abs_1h) DESC\nLIMIT 10",
       "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT * EXCEPT (rank_out, _fund_1h_min, _fund_1h_max)\nFROM (\n    SELECT\n        ccid,\n        truncate(_fund_1h_max - _fund_1h_min, 6) diff_abs_1h,\n        truncate(_fund_1h_max * 8 - _fund_1h_min * 8, 6) diff_abs_8h,\n        first_value(ex) OVER w_asc AS ex_min,\n        first_value(ex) OVER w_desc AS ex_max,\n        first_value(ts) OVER w_asc AS ts_min,\n        first_value(ts) OVER w_desc AS ts_max,\n        token_1,\n        first_value(funding_rate_1h) OVER w_asc AS _fund_1h_min,\n        first_value(funding_rate_1h) OVER w_desc AS _fund_1h_max,\n        truncate(_fund_1h_min, 6) fund_1h_min,\n        truncate(_fund_1h_max, 6) fund_1h_max,\n        truncate(_fund_1h_min * 8, 6) fund_8h_min,\n        truncate(_fund_1h_max * 8, 6) fund_8h_max,\n        row_number() OVER (PARTITION BY ccid) rank_out\n    FROM (\n        SELECT * EXCEPT (rank)\n        FROM (\n            SELECT\n                t1.ex,\n                conv_symbol_to_token_v2(t1.ex, s) token_1,\n                t1.funding_rate / t1.funding_hours funding_rate_1h,\n                row_number() OVER (PARTITION BY ex, s ORDER BY ts DESC) AS rank,\n                t2.ccid,\n                toDateTime(t1.ts / 1000) ts\n            FROM (\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, toUInt64(t2.fundingInterval / 60) funding_hours\n                    FROM (\n                        SELECT *\n                        FROM default.tickers\n                        WHERE ex = 'bybit' AND k = 'fut'\n                    ) t1\n                    INNER JOIN (\n                        SELECT *\n                        FROM default.t_bybit_2025_01_02\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, funding_hours\n                    FROM (\n                        SELECT *\n                        FROM default.tickers\n                        WHERE ex = 'gateio' AND k = 'fut'\n                    ) t1\n                    INNER JOIN (\n                        SELECT s, toUInt64(JSONExtract(contract_raw, 'funding_interval', 'UInt64') / 60 / 60) funding_hours\n                        FROM default.t_gateio_2025_01_02\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'hyperliquid'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'arkm'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, fundingInterval funding_hours\n                    FROM default.fundings_curr_2025_01_12 t1\n                    INNER JOIN (\n                        SELECT s, fundingInterval\n                        FROM default.t_paradex_2025_01_21\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                    WHERE ex = 'paradex'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate / 10e17 funding_rate, ts * 1000 ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'polynomial-fi'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.tickers\n                    WHERE ex = 'apex-pro'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.tickers\n                    WHERE ex = 'apex-omni'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'aevo'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate, ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'bitunix'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'coinex'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'bingx'\n                )\n            ) t1\n            INNER JOIN (\n                SELECT *\n                FROM default.ex_k_to_ccid\n                WHERE k = 'fut'\n            ) t2\n                ON t1.ex = t2.ex AND token_1 = t2.base\n            WHERE t2.ccid != ''\n                AND startsWith(notes, 'not-on-ui-on-') = 0\n                AND startsWith(notes, 'delisted-on-') = 0\n                AND startsWith(notes, 'index-fut-custom-for-ex-') = 0\n                AND ts_write >= NOW() - INTERVAL 30 MINUTE\n        )\n        WHERE rank = 1\n    )\n    WINDOW w_asc AS (PARTITION BY ccid ORDER BY funding_rate_1h ASC),\n        w_desc AS (PARTITION BY ccid ORDER BY funding_rate_1h DESC)\n)\nWHERE rank_out = 1\nORDER BY abs(diff_abs_1h) DESC\nLIMIT 10",
       "round": "0s"
      }
     ]
    },
    {
     "title": "funding-raw",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 165 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  toDateTime(t1.ts_write) ts_write,\n  conv_symbol_to_token_v2(ex, s) token_1,\n  t1.funding_rate\nFROM (\n  SELECT ex, k, ts_write, s, funding_rate\n  FROM default.fundings_curr_2025_01_12\n  UNION ALL\n  SELECT ex, k, ts_write, s, funding_rate\n  FROM default.tickers\n) t1\nINNER JOIN (\n  SELECT *\n  FROM default.ex_k_to_ccid\n  WHERE k = 'fut'\n) t2\n  ON t1.ex = t2.ex AND token_1 = t2.base\nWHERE t2.ccid != ''\n  AND ts_write BETWEEN toDateTime($from) AND toDateTime($to)\n  AND t1.k = 'fut'\n  AND t1.ex = '$var_fundings_ex'\n  AND t2.ccid = '$var_fundings_ccid'\nORDER BY ts_write",
       "rawQuery": "/* grafana dashboard=default, user=1 */\nSELECT\n  toDateTime(t1.ts_write) ts_write,\n  conv_symbol_to_token_v2(ex, s) token_1,\n  t1.funding_rate\nFROM (\n  SELECT ex, k, ts_write, s, funding_rate\n  FROM default.fundings_curr_2025_01_12\n  UNION ALL\n  SELECT ex, k, ts_write, s, funding_rate\n  FROM default.tickers\n) t1\nINNER JOIN (\n  SELECT *\n  FROM default.ex_k_to_ccid\n  WHERE k = 'fut'\n) t2\n  ON t1.ex = t2.ex AND token_1 = t2.base\nWHERE t2.ccid != ''\n  AND ts_write BETWEEN toDateTime(1744596069) AND toDateTime(1744617669)\n  AND t1.k = 'fut'\n  AND t1.ex = 'bingx'\n  AND t2.ccid = 'melania-meme'\nORDER BY ts_write",
       "round": "0s"
      }
     ]
    }
   ]
  }
 ]
}