{
 "title": "fundings",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "var_ex",
    "label": "var_ex",
    "query": "SELECT DISTINCT ex\nFROM (\n  SELECT ex\n  FROM default.tickers\n  UNION ALL\n  SELECT ex\n  FROM default.fundings_curr_2025_01_12\n)"
   },
   {
    "name": "var_ccid",
    "label": "var_ccid",
    "query": "SELECT DISTINCT ccid\nFROM default.ex_k_to_ccid\nWHERE ccid != ''"
   }
  ]
 },
 "panels": [
  {
   "title": "fundings-curr",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * EXCEPT (rank_out, _fund_1h_min, _fund_1h_max)\nFROM (\n    SELECT\n        ccid,\n        truncate(_fund_1h_max - _fund_1h_min, 6) diff_abs_1h,\n        truncate(_fund_1h_max * 8 - _fund_1h_min * 8, 6) diff_abs_8h,\n        first_value(ex) OVER w_asc AS ex_min,\n        first_value(ex) OVER w_desc AS ex_max,\n        first_value(ts) OVER w_asc AS ts_min,\n        first_value(ts) OVER w_desc AS ts_max,\n        token_1,\n        first_value(funding_rate_1h) OVER w_asc AS _fund_1h_min,\n        first_value(funding_rate_1h) OVER w_desc AS _fund_1h_max,\n        truncate(_fund_1h_min, 6) fund_1h_min,\n        truncate(_fund_1h_max, 6) fund_1h_max,\n        truncate(_fund_1h_min * 8, 6) fund_8h_min,\n        truncate(_fund_1h_max * 8, 6) fund_8h_max,\n        row_number() OVER (PARTITION BY ccid) rank_out\n    FROM (\n        SELECT * EXCEPT (rank)\n        FROM (\n            SELECT\n                t1.ex,\n                conv_symbol_to_token_v2(t1.ex, s) token_1,\n                t1.funding_rate / t1.funding_hours funding_rate_1h,\n                row_number() OVER (PARTITION BY ex, s ORDER BY ts DESC) AS rank,\n                t2.ccid,\n                toDateTime(t1.ts / 1000) ts\n            FROM (\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, toUInt64(t2.funding_interval / 60) funding_hours\n                    FROM (\n                        SELECT *\n                        FROM default.tickers\n                        WHERE ex = 'bybit' AND k = 'fut'\n                    ) t1\n                    INNER JOIN (\n                        SELECT s, funding_interval\n                        FROM default.bybit_instruments_info\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, funding_hours\n                    FROM (\n                        SELECT *\n                        FROM default.tickers\n                        WHERE ex = 'gateio' AND k = 'fut'\n                    ) t1\n                    INNER JOIN (\n                        SELECT s, toUInt64(JSONExtract(contract_raw, 'funding_interval', 'UInt64') / 60 / 60) funding_hours\n                        FROM default.gateio_contracts\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'hyperliquid'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'arkm'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, funding_interval funding_hours\n                    FROM (\n                        SELECT *\n                        FROM default.fundings_curr_2025_01_12\n                        WHERE ex = 'paradex'\n                    ) t1\n                    INNER JOIN (\n                        SELECT s, funding_interval\n                        FROM default.paradex_markets\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate / 10e17 funding_rate, ts * 1000 ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'polynomial-fi'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.tickers\n                    WHERE ex = 'apex-pro'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.tickers\n                    WHERE ex = 'apex-omni'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'aevo'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate, ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'bitunix'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'coinex'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'bingx'\n                )\n            ) t1\n            INNER JOIN (\n                SELECT *\n                FROM default.ex_k_to_ccid\n                WHERE k = 'fut'\n            ) t2\n                ON t1.ex = t2.ex AND token_1 = t2.base\n            WHERE t2.ccid != ''\n                AND startsWith(notes, 'not-on-ui-on-') = 0\n                AND startsWith(notes, 'delisted-on-') = 0\n                AND startsWith(notes, 'index-fut-custom-for-ex-') = 0\n                AND ts_write >= NOW() - INTERVAL 30 MINUTE\n        )\n        WHERE rank = 1\n    )\n    WINDOW w_asc AS (PARTITION BY ccid ORDER BY funding_rate_1h ASC),\n        w_desc AS (PARTITION BY ccid ORDER BY funding_rate_1h DESC)\n)\nWHERE rank_out = 1\nORDER BY abs(diff_abs_1h) DESC\nLIMIT 10",
     "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT * EXCEPT (rank_out, _fund_1h_min, _fund_1h_max)\nFROM (\n    SELECT\n        ccid,\n        truncate(_fund_1h_max - _fund_1h_min, 6) diff_abs_1h,\n        truncate(_fund_1h_max * 8 - _fund_1h_min * 8, 6) diff_abs_8h,\n        first_value(ex) OVER w_asc AS ex_min,\n        first_value(ex) OVER w_desc AS ex_max,\n        first_value(ts) OVER w_asc AS ts_min,\n        first_value(ts) OVER w_desc AS ts_max,\n        token_1,\n        first_value(funding_rate_1h) OVER w_asc AS _fund_1h_min,\n        first_value(funding_rate_1h) OVER w_desc AS _fund_1h_max,\n        truncate(_fund_1h_min, 6) fund_1h_min,\n        truncate(_fund_1h_max, 6) fund_1h_max,\n        truncate(_fund_1h_min * 8, 6) fund_8h_min,\n        truncate(_fund_1h_max * 8, 6) fund_8h_max,\n        row_number() OVER (PARTITION BY ccid) rank_out\n    FROM (\n        SELECT * EXCEPT (rank)\n        FROM (\n            SELECT\n                t1.ex,\n                conv_symbol_to_token_v2(t1.ex, s) token_1,\n                t1.funding_rate / t1.funding_hours funding_rate_1h,\n                row_number() OVER (PARTITION BY ex, s ORDER BY ts DESC) AS rank,\n                t2.ccid,\n                toDateTime(t1.ts / 1000) ts\n            FROM (\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, toUInt64(t2.fundingInterval / 60) funding_hours\n                    FROM (\n                        SELECT *\n                        FROM default.tickers\n                        WHERE ex = 'bybit' AND k = 'fut'\n                    ) t1\n                    INNER JOIN (\n                        SELECT *\n                        FROM default.t_bybit_2025_01_02\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, funding_hours\n                    FROM (\n                        SELECT *\n                        FROM default.tickers\n                        WHERE ex = 'gateio' AND k = 'fut'\n                    ) t1\n                    INNER JOIN (\n                        SELECT s, toUInt64(JSONExtract(contract_raw, 'funding_interval', 'UInt64') / 60 / 60) funding_hours\n                        FROM default.t_gateio_2025_01_02\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'hyperliquid'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'arkm'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, fundingInterval funding_hours\n                    FROM default.fundings_curr_2025_01_12 t1\n                    INNER JOIN (\n                        SELECT s, fundingInterval\n                        FROM default.t_paradex_2025_01_21\n                        WHERE k = 'fut'\n                    ) t2\n                        ON t1.s = t2.s\n                    WHERE ex = 'paradex'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate / 10e17 funding_rate, ts * 1000 ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'polynomial-fi'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.tickers\n                    WHERE ex = 'apex-pro'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.tickers\n                    WHERE ex = 'apex-omni'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 1 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'aevo'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate, ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'bitunix'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'coinex'\n                )\n                UNION ALL\n                SELECT *\n                FROM (\n                    SELECT s, funding_rate * 100 funding_rate, ts * 1000 ts, ex, k, ts_write, 8 funding_hours\n                    FROM default.fundings_curr_2025_01_12\n                    WHERE ex = 'bingx'\n                )\n            ) t1\n            INNER JOIN (\n                SELECT *\n                FROM default.ex_k_to_ccid\n                WHERE k = 'fut'\n            ) t2\n                ON t1.ex = t2.ex AND token_1 = t2.base\n            WHERE t2.ccid != ''\n                AND startsWith(notes, 'not-on-ui-on-') = 0\n                AND startsWith(notes, 'delisted-on-') = 0\n                AND startsWith(notes, 'index-fut-custom-for-ex-') = 0\n                AND ts_write >= NOW() - INTERVAL 30 MINUTE\n        )\n        WHERE rank = 1\n    )\n    WINDOW w_asc AS (PARTITION BY ccid ORDER BY funding_rate_1h ASC),\n        w_desc AS (PARTITION BY ccid ORDER BY funding_rate_1h DESC)\n)\nWHERE rank_out = 1\nORDER BY abs(diff_abs_1h) DESC\nLIMIT 10",
     "round": "0s"
    }
   ]
  },
  {
   "title": "last-write-by-ex",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    ex,\n    max(ts_write) AS last_write\nFROM default.fundings_curr_2025_01_12\nWHERE toDate(ts_write) = today()\nGROUP BY ex\nORDER BY last_write ASC",
     "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT\n    ex,\n    max(ts_write) AS last_write\nFROM default.fundings_curr_2025_01_12\nWHERE toDate(ts_write) = today()\nGROUP BY ex\nORDER BY last_write AS",
     "round": "0s"
    }
   ]
  },
  {
   "title": "non-matched-tokens-with-ccid",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  t1.*,\n  conv_symbol_to_token_v2(t1.ex, t1.s) token_1,\n  t2.ccid\nFROM (\n  SELECT DISTINCT ex, s, k\n  FROM (\n    SELECT ex, s, k\n    FROM default.fundings_curr_2025_01_12\n    UNION ALL\n    SELECT ex, s, k\n    FROM default.tickers\n  )\n  WHERE k = 'fut' AND ex != 'binance'\n) t1\nLEFT JOIN (\n  SELECT *\n  FROM default.ex_k_to_ccid\n  WHERE k = 'fut'\n) t2\n  ON t1.ex = t2.ex AND token_1 = t2.base\nWHERE t2.ccid = ''\n  AND startsWith(notes, 'not-on-ui-on-') = 0\n  AND startsWith(notes, 'delisted-on-') = 0\n  AND startsWith(notes, 'index-fut-custom-for-ex-') = 0\nORDER BY ex, s",
     "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT\n  t1.*,\n  conv_symbol_to_token_v2(t1.ex, t1.symbol) token_1,\n  t2.ccid\nFROM (\n  SELECT ex, symbol\n  FROM default.fundings_curr_2025_01_12\n  GROUP BY ex, symbol\n) t1\nLEFT JOIN (\n  SELECT *\n  FROM default.ex_k_to_ccid\n  WHERE k = 'fut'\n) t2\n  ON t1.ex = t2.ex AND token_1 = t2.base\nWHERE t2.ccid = ''\n  AND startsWith(notes, 'not-on-ui-on-') = 0\n  AND startsWith(notes, 'delisted-on-') = 0\n  AND startsWith(notes, 'index-fut-custom-for-ex-') = 0\nORDER BY ex, symbol",
     "round": "0s"
    }
   ]
  },
  {
   "title": "funding-raw",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  toDateTime(t1.ts_write) ts_write,\n  conv_symbol_to_token_v2(ex, s) token_1,\n  t1.funding_rate\nFROM (\n  SELECT ex, k, ts_write, s, funding_rate\n  FROM default.fundings_curr_2025_01_12\n  UNION ALL\n  SELECT ex, k, ts_write, s, funding_rate\n  FROM default.tickers\n) t1\nINNER JOIN (\n  SELECT *\n  FROM default.ex_k_to_ccid\n  WHERE k = 'fut'\n) t2\n  ON t1.ex = t2.ex AND token_1 = t2.base\nWHERE t2.ccid != ''\n  AND ts_write BETWEEN toDateTime($from) AND toDateTime($to)\n  AND t1.k = 'fut'\n  AND t1.ex = '$var_ex'\n  AND t2.ccid = '$var_ccid'\nORDER BY ts_write",
     "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT\n  toDateTime(t1.ts_write) ts_write,\n  conv_symbol_to_token_v2(ex, s) token_1,\n  t1.funding_rate\nFROM (\n  SELECT ex, k, ts_write, s, funding_rate\n  FROM default.fundings_curr_2025_01_12\n  UNION ALL\n  SELECT ex, k, ts_write, s, funding_rate\n  FROM default.tickers\n) t1\nINNER JOIN (\n  SELECT *\n  FROM default.ex_k_to_ccid\n  WHERE k = 'fut'\n) t2\n  ON t1.ex = t2.ex AND token_1 = t2.base\nWHERE t2.ccid != ''\n  AND ts_writ BETWEEN toDateTime(1740312024) AND toDateTime(1740333624)\n  AND t1.k = 'fut'\n  AND t1.ex = 'bingx'\n  AND t2.ccid = 'melania-meme'\nORDER BY ts_write",
     "round": "0s"
    }
   ]
  },
  {
   "title": "duplicates-ccid",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ex, base, count() AS amount\nFROM default.ex_k_to_ccid\nWHERE k = 'fut'\nGROUP BY ex, base\nHAVING amount != 1",
     "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT ex, base, count() AS amount\nFROM default.ex_k_to_ccid\nWHERE k = 'fut'\nGROUP BY ex, base\nHAVING amount != 1",
     "round": "0s"
    }
   ]
  },
  {
   "title": "non-on-ui-ccid",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT ex, base, notes\nFROM default.ex_k_to_ccid\nWHERE k = 'fut' AND startsWith(notes, 'not-on-ui-on-')",
     "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT ex, base, notes\nFROM default.ex_k_to_ccid\nWHERE k = 'fut' AND startsWith(notes, 'not-on-ui-on-')",
     "round": "0s"
    }
   ]
  },
  {
   "title": "parts-amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count()\nFROM system.parts\nWHERE (database = 'default') AND (`table` = 'fundings_curr_2025_01_12')",
     "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT count()\nFROM system.parts\nWHERE (database = 'default') AND (`table` = 'fundings_curr_2025_01_12')",
     "round": "0s"
    }
   ]
  },
  {
   "title": "partitions-amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count()\nFROM (\n  SELECT partition\n  FROM system.parts\n  WHERE (database = 'default') AND (`table` = 'fundings_curr_2025_01_12')\n  GROUP BY partition\n)",
     "rawQuery": "/* grafana dashboard=fundings, user=1 */\nSELECT count()\nFROM (\n  SELECT partition\n  FROM system.parts\n  WHERE (database = 'default') AND (`table` = 'fundings_curr_2025_01_12')\n  GROUP BY partition\n)",
     "round": "0s"
    }
   ]
  }
 ]
}