{
 "title": "spreads-curr-rasul-hasanov",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "spread-fut-exp-perp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "-- NOTE: to add binance here i must concat and one tables to 2 subqueries\nSELECT\n  t1.ts_bucket,\n  CONCAT(t1.ex, '-', t1.s, '-vs-', t2.s) t,\n  sum((t1.p_bid - t2.p_bid - (t1.fair_premium * t2.p_bid)) / t2.p_bid * 100) spread_rel\nFROM (\n  WITH 10.95 * 0.01 AS risk_free_rate  -- riskFreeRateConst * riskFreerateMlt\n  SELECT\n    s,\n    ex,\n    regexpExtract(s, '^([A-Z]+?)(?:USDT-|-)') token_1,\n    toFloat64OrZero(JSON_VALUE(obj_raw, '$.bid1Price')) p_bid,\n    (toDateTime(toUInt64OrZero(JSON_VALUE(obj_raw, '$.deliveryTime')) / 1000) - now()) / (365*24*60*60) * risk_free_rate fair_premium,\n    toStartOfHour(ts_write) ts_bucket,\n    row_number() OVER (PARTITION BY s, ts_bucket ORDER BY ts_write DESC) as rank_last_event\n  FROM default.tickers\n  WHERE ex = 'bybit'\n    AND k = 'fut'\n    AND s like '%-%'\n    AND p_bid != 0\n    AND ts_write BETWEEN toDateTime($from) AND toDateTime($to)\n  UNION ALL\n  SELECT\n    s,\n    ex,\n    conv_symbol_to_token_v2(ex, s) token_1,\n    toFloat64(JSON_VALUE(obj_raw, '$.bidPrice')) p_bid,\n    (parseDateTime(regexpExtract(s, '_(\\d*)$'), '%y%m%d') - NOW()) / (365*24*60*60) * risk_free_rate fair_premium,\n    toStartOfHour(ts_write) ts_bucket,\n    row_number() OVER (PARTITION BY s, ts_bucket ORDER BY ts_write DESC) as rank_last_event\n  FROM default.tickers\n  WHERE ex = 'binance'\n    AND k = 'fut'\n    AND s LIKE '%\\_%'\n    AND ts_write BETWEEN toDateTime($from) AND toDateTime($to)\n) t1\nLEFT JOIN (\n  SELECT\n    t1.s s,\n    t1.ex ex,\n    t2.base_coin token_1,\n    p_bid,\n    toStartOfHour(ts_write) ts_bucket,\n    row_number() OVER (PARTITION BY s, ts_bucket ORDER BY ts_write DESC) as rank_last_event\n  FROM (\n    SELECT s, ex, k, ts_write, toFloat64OrZero(JSON_VALUE(obj_raw, '$.bid1Price')) p_bid\n    FROM default.tickers\n    WHERE ex = 'bybit'\n      AND k = 'fut'\n      AND s NOT LIKE '%-%'\n      AND p_bid != 0\n      AND ts_write BETWEEN toDateTime($from) AND toDateTime($to)\n  ) t1\n  LEFT JOIN (\n    SELECT s, k, base_coin\n    FROM default.bybit_instruments_info\n    WHERE quote_coin in ('USDE', 'USDT', 'USDC')\n  ) t2\n    ON t1.s = t2.s AND t1.k = t2.k\n  UNION ALL\n  SELECT\n    s,\n    ex,\n    conv_symbol_to_token_v2(ex, s) token_1,\n    toFloat64(JSON_VALUE(obj_raw, '$.bidPrice')) p_bid,\n    toStartOfHour(ts_write) ts_bucket,\n    row_number() OVER (PARTITION BY s, ts_bucket ORDER BY ts_write DESC) as rank_last_event\n  FROM default.tickers\n  WHERE ex = 'binance'\n    AND k = 'fut'\n    AND s NOT LIKE '%\\_%'\n    AND ts_write BETWEEN toDateTime($from) AND toDateTime($to)\n) t2\n  ON t1.token_1 = t2.token_1\n    AND t1.ts_bucket = t2.ts_bucket\n    AND t1.ex = t2.ex\nWHERE t1.rank_last_event = 1\n  AND t2.rank_last_event = 1\nGROUP BY t, ts_bucket\nORDER BY t, ts_bucket DESC",
     "rawQuery": "/* grafana dashboard=spreads-curr-rasul-hasanov, user=1 */\n\nSELECT\n  t1.ts_bucket,\n  CONCAT(t1.ex, '-', t1.s, '-vs-', t2.s) t,\n  sum((t1.p_bid - t2.p_bid - (t1.fair_premium * t2.p_bid)) / t2.p_bid * 100) spread_rel\nFROM (\n  WITH 10.95 * 0.01 AS risk_free_rate  \n  SELECT\n    s,\n    ex,\n    regexpExtract(s, '^([A-Z]+?)(?:USDT-|-)') token_1,\n    toFloat64OrZero(JSON_VALUE(obj_raw, '$.bid1Price')) p_bid,\n    (toDateTime(toUInt64OrZero(JSON_VALUE(obj_raw, '$.deliveryTime')) / 1000) - now()) / (365*24*60*60) * risk_free_rate fair_premium,\n    toStartOfHour(ts_write) ts_bucket,\n    row_number() OVER (PARTITION BY s, ts_bucket ORDER BY ts_write DESC) as rank_last_event\n  FROM default.tickers\n  WHERE ex = 'bybit'\n    AND k = 'fut'\n    AND s like '%-%'\n    AND p_bid != 0\n    AND ts_write BETWEEN toDateTime(1740774438) AND toDateTime(1740947238)\n  UNION ALL\n  SELECT\n    s,\n    ex,\n    conv_symbol_to_token_v2(ex, s) token_1,\n    toFloat64(JSON_VALUE(obj_raw, '$.bidPrice')) p_bid,\n    (parseDateTime(regexpExtract(s, '_(\\d*)$'), '%y%m%d') - NOW()) / (365*24*60*60) * risk_free_rate fair_premium,\n    toStartOfHour(ts_write) ts_bucket,\n    row_number() OVER (PARTITION BY s, ts_bucket ORDER BY ts_write DESC) as rank_last_event\n  FROM default.tickers\n  WHERE ex = 'binance'\n    AND k = 'fut'\n    AND s LIKE '%\\_%'\n    AND ts_write BETWEEN toDateTime(1740774438) AND toDateTime(1740947238)\n) t1\nLEFT JOIN (\n  SELECT\n    t1.s s,\n    t1.ex ex,\n    t2.base_coin token_1,\n    p_bid,\n    toStartOfHour(ts_write) ts_bucket,\n    row_number() OVER (PARTITION BY s, ts_bucket ORDER BY ts_write DESC) as rank_last_event\n  FROM (\n    SELECT s, ex, k, ts_write, toFloat64OrZero(JSON_VALUE(obj_raw, '$.bid1Price')) p_bid\n    FROM default.tickers\n    WHERE ex = 'bybit'\n      AND k = 'fut'\n      AND s NOT LIKE '%-%'\n      AND p_bid != 0\n      AND ts_write BETWEEN toDateTime(1740774438) AND toDateTime(1740947238)\n  ) t1\n  LEFT JOIN (\n    SELECT s, k, base_coin\n    FROM default.bybit_instruments_info\n    WHERE quote_coin in ('USDE', 'USDT', 'USDC')\n  ) t2\n    ON t1.s = t2.s AND t1.k = t2.k\n  UNION ALL\n  SELECT\n    s,\n    ex,\n    conv_symbol_to_token_v2(ex, s) token_1,\n    toFloat64(JSON_VALUE(obj_raw, '$.bidPrice')) p_bid,\n    toStartOfHour(ts_write) ts_bucket,\n    row_number() OVER (PARTITION BY s, ts_bucket ORDER BY ts_write DESC) as rank_last_event\n  FROM default.tickers\n  WHERE ex = 'binance'\n    AND k = 'fut'\n    AND s NOT LIKE '%\\_%'\n    AND ts_write BETWEEN toDateTime(1740774438) AND toDateTime(1740947238)\n) t2\n  ON t1.token_1 = t2.token_1\n    AND t1.ts_bucket = t2.ts_bucket\n    AND t1.ex = t2.ex\nWHERE t1.rank_last_event = 1\n  AND t2.rank_last_event = 1\nGROUP BY t, ts_bucket\nORDER BY t, ts_bucket DESC",
     "round": "0s"
    }
   ]
  },
  { "title": "curr-bybit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "fut-perp vs spot",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    ex,\n    ccid,\n    truncate((p_fut - p_spot) / p_spot * 100, 2) diff_rel,\n    sum(if(k = 'fut', p_bid_per_1_token, 0)) p_fut,\n    sum(if(k = 'spot', p_bid_per_1_token, 0)) p_spot,\n    groupArrayIf(ts_write, k = 'fut') ts_write_fut,\n    groupArrayIf(ts_write, k = 'spot') ts_write_spot,\n    groupArrayIf(s, k = 'fut') s_fut,\n    groupArrayIf(s, k = 'spot') s_spot,\n    groupArrayIf(p_bid, k = 'fut') p_bid_fut,\n    groupArrayIf(p_bid, k = 'spot') p_bid_spot,\n    groupArrayIf(ex, k = 'fut') ex_fut,\n    groupArrayIf(ex, k = 'spot') ex_spot\nFROM (\n    SELECT\n        t1.ex ex,\n        t1.s s,\n        t1.k k,\n        t1.ts_write ts_write,\n        if(t1.k = 'fut', replaceRegexpOne(t2.base_coin, '^(100*)', ''), t2.base_coin) token_1,\n        t3.ccid,\n        p_bid,\n        multiIf(\n            (ex, k, s) = ('bybit', 'fut', 'SHIB1000PERP'), p_bid / pow(10, 3),\n            k = 'fut', p_bid / pow(10, LENGTH(regexpExtract(t2.base_coin, '^1(0*)'))),\n            p_bid\n        ) p_bid_per_1_token,\n        row_number() OVER (PARTITION BY ex, k, ccid ORDER BY ts_write DESC) as rank_last_event\n    FROM (\n        SELECT ex, s, k, ts_write,\n            toFloat64(JSON_VALUE(obj_raw, '$.bid1Price')) p_bid\n        FROM default.tickers\n        WHERE ex = 'bybit'\n            AND ts_write >= NOW() - INTERVAL 30 MINUTE\n    ) t1\n    LEFT JOIN (\n        SELECT s, k, base_coin\n        FROM default.bybit_instruments_info\n        WHERE quote_coin in ('USDE', 'USDT', 'USDC')\n    ) t2\n        ON t1.s = t2.s AND t1.k = t2.k\n    LEFT JOIN (\n        SELECT *\n        FROM default.ex_k_to_ccid\n        WHERE ex = 'bybit'\n    ) t3\n        ON token_1 = t3.base AND t1.k = t3.k\n    WHERE t2.base_coin != '' AND t3.ccid != ''\n)\nWHERE rank_last_event = 1\nGROUP BY ex, ccid\nHAVING p_fut != 0 AND p_spot != 0\nORDER BY diff_rel DESC\nLIMIT 20",
     "rawQuery": "/* grafana dashboard=spreads-curr-rasul-hasanov, user=1 */\nSELECT\n    ex,\n    ccid,\n    truncate((p_fut - p_spot) / p_spot * 100, 2) diff_rel,\n    sum(if(k = 'fut', p_bid_per_1_token, 0)) p_fut,\n    sum(if(k = 'spot', p_bid_per_1_token, 0)) p_spot,\n    groupArrayIf(ts_write, k = 'fut') ts_write_fut,\n    groupArrayIf(ts_write, k = 'spot') ts_write_spot,\n    groupArrayIf(s, k = 'fut') s_fut,\n    groupArrayIf(s, k = 'spot') s_spot,\n    groupArrayIf(p_bid, k = 'fut') p_bid_fut,\n    groupArrayIf(p_bid, k = 'spot') p_bid_spot,\n    groupArrayIf(ex, k = 'fut') ex_fut,\n    groupArrayIf(ex, k = 'spot') ex_spot\nFROM (\n    SELECT\n        t1.ex ex,\n        t1.s s,\n        t1.k k,\n        t1.ts_write ts_write,\n        if(t1.k = 'fut', replaceRegexpOne(t2.base_coin, '^(100*)', ''), t2.base_coin) token_1,\n        t3.ccid,\n        p_bid,\n        multiIf(\n            (ex, k, s) = ('bybit', 'fut', 'SHIB1000PERP'), p_bid / pow(10, 3),\n            k = 'fut', p_bid / pow(10, LENGTH(regexpExtract(t2.base_coin, '^1(0*)'))),\n            p_bid\n        ) p_bid_per_1_token,\n        row_number() OVER (PARTITION BY ex, k, ccid ORDER BY ts_write DESC) as rank_last_event\n    FROM (\n        SELECT ex, s, k, ts_write,\n            toFloat64(JSON_VALUE(obj_raw, '$.bid1Price')) p_bid\n        FROM default.tickers\n        WHERE ex = 'bybit'\n            AND ts_write >= NOW() - INTERVAL 30 MINUTE\n    ) t1\n    LEFT JOIN (\n        SELECT s, k, base_coin\n        FROM default.bybit_instruments_info\n        WHERE quote_coin in ('USDE', 'USDT', 'USDC')\n    ) t2\n        ON t1.s = t2.s AND t1.k = t2.k\n    LEFT JOIN (\n        SELECT *\n        FROM default.ex_k_to_ccid\n        WHERE ex = 'bybit'\n    ) t3\n        ON token_1 = t3.base AND t1.k = t3.k\n    WHERE t2.base_coin != '' AND t3.ccid != ''\n)\nWHERE rank_last_event = 1\nGROUP BY ex, ccid\nHAVING p_fut != 0 AND p_spot != 0\nORDER BY diff_rel DESC\nLIMIT 20",
     "round": "0s"
    }
   ]
  },
  {
   "title": "fut-perp vs fut-exp",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 13 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    t1.token_1,\n    t1.s s_fut_exp,\n    t2.s s_fut_perp,\n    truncate((p_fut_exp - p_fut_perp) / p_fut_perp * 100, 4) diff_rel,\n    t1.p_bid p_fut_exp,\n    t2.p_bid p_fut_perp,\n    t1.fair_premium * p_fut_perp spread_fair,\n    -- NOTE: source formulas are here https://ru.tradingview.com/v/9HzSne1K/\n    (p_fut_exp - p_fut_perp - spread_fair) / p_fut_perp * 100 spread_rel\nFROM (\n    WITH 10.95 * 0.01 AS risk_free_rate  -- riskFreeRateConst * riskFreerateMlt\n    SELECT\n        s,\n        regexpExtract(s, '^([A-Z]+?)(?:USDT-|-)') token_1,\n        toFloat64OrZero(JSON_VALUE(obj_raw, '$.bid1Price')) p_bid,\n        (toDateTime(toUInt64OrZero(JSON_VALUE(obj_raw, '$.deliveryTime')) / 1000) - now()) / (365*24*60*60) * risk_free_rate fair_premium,\n        row_number() OVER (PARTITION BY token_1, s ORDER BY ts_write DESC) as rank_last_event\n    FROM default.tickers\n    WHERE ex = 'bybit' AND k = 'fut' AND s like '%-%' AND p_bid != 0\n        AND ts_write >= NOW() - INTERVAL 30 MINUTE\n) t1\nLEFT JOIN (\n    SELECT\n        t1.s s,\n        t2.base_coin token_1,\n        p_bid,\n        row_number() OVER (PARTITION BY token_1, s ORDER BY ts_write DESC) as rank_last_event\n    FROM (\n        SELECT s, k, ts_write, toFloat64OrZero(JSON_VALUE(obj_raw, '$.bid1Price')) p_bid\n        FROM default.tickers\n        WHERE ex = 'bybit' AND k = 'fut' AND s not like '%-%' AND p_bid != 0\n            AND ts_write >= NOW() - INTERVAL 30 MINUTE\n    ) t1\n    LEFT JOIN (\n        SELECT s, k, base_coin\n        FROM default.bybit_instruments_info\n        WHERE quote_coin in ('USDE', 'USDT', 'USDC')\n    ) t2\n        ON t1.s = t2.s AND t1.k = t2.k\n) t2\n    ON t1.token_1 = t2.token_1\nWHERE t1.rank_last_event = 1 AND t2.rank_last_event = 1\nORDER BY abs(diff_rel) DESC",
     "rawQuery": "/* grafana dashboard=spreads-curr-rasul-hasanov, user=1 */\nSELECT\n    t1.token_1,\n    t1.s s_fut_exp,\n    t2.s s_fut_perp,\n    truncate((p_fut_exp - p_fut_perp) / p_fut_perp * 100, 4) diff_rel,\n    t1.p_bid p_fut_exp,\n    t2.p_bid p_fut_perp,\n    t1.fair_premium * p_fut_perp spread_fair,\n    \n    (p_fut_exp - p_fut_perp - spread_fair) / p_fut_perp * 100 spread_rel\nFROM (\n    WITH 10.95 * 0.01 AS risk_free_rate  \n    SELECT\n        s,\n        regexpExtract(s, '^([A-Z]+?)(?:USDT-|-)') token_1,\n        toFloat64OrZero(JSON_VALUE(obj_raw, '$.bid1Price')) p_bid,\n        (toDateTime(toUInt64OrZero(JSON_VALUE(obj_raw, '$.deliveryTime')) / 1000) - now()) / (365*24*60*60) * risk_free_rate fair_premium,\n        row_number() OVER (PARTITION BY token_1, s ORDER BY ts_write DESC) as rank_last_event\n    FROM default.tickers\n    WHERE ex = 'bybit' AND k = 'fut' AND s like '%-%' AND p_bid != 0\n        AND ts_write >= NOW() - INTERVAL 30 MINUTE\n) t1\nLEFT JOIN (\n    SELECT\n        t1.s s,\n        t2.base_coin token_1,\n        p_bid,\n        row_number() OVER (PARTITION BY token_1, s ORDER BY ts_write DESC) as rank_last_event\n    FROM (\n        SELECT s, k, ts_write, toFloat64OrZero(JSON_VALUE(obj_raw, '$.bid1Price')) p_bid\n        FROM default.tickers\n        WHERE ex = 'bybit' AND k = 'fut' AND s not like '%-%' AND p_bid != 0\n            AND ts_write >= NOW() - INTERVAL 30 MINUTE\n    ) t1\n    LEFT JOIN (\n        SELECT s, k, base_coin\n        FROM default.bybit_instruments_info\n        WHERE quote_coin in ('USDE', 'USDT', 'USDC')\n    ) t2\n        ON t1.s = t2.s AND t1.k = t2.k\n) t2\n    ON t1.token_1 = t2.token_1\nWHERE t1.rank_last_event = 1 AND t2.rank_last_event = 1\nORDER BY abs(diff_re) DESC",
     "round": "0s"
    }
   ]
  },
  {
   "title": "curr-binance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "fut-perp vs spot",
     "type": "table",
     "gridPos": { "h": 2, "w": 16, "x": 0, "y": 40 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "select 'TODO: binance fut-per vs spot' as t",
       "rawQuery": "/* grafana dashboard=spreads-curr-rasul-hasanov, user=1 */\nselect 'TODO: binance fut-per vs spot' as t",
       "round": "0s"
      }
     ]
    },
    {
     "title": "fut-perp vs fut-exp",
     "type": "timeseries",
     "gridPos": { "h": 2, "w": 16, "x": 0, "y": 42 },
     "targets": [
      {
       "contextWindowSize": "10",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "select 1 t",
       "rawQuery": "/* grafana dashboard=spreads-curr-rasul-hasanov, user=1 */\nselect 1 t",
       "round": "0s"
      }
     ]
    }
   ]
  }
 ]
}