apiVersion: 1
deleteDatasources:
- name: clickhouse-1
  orgId: 1
datasources:
- name: clickhouse-1
  type: vertamedia-clickhouse-datasource
  orgId: 1
  url: http://clickhouse-1:8123
  password:
  user:
  database: default
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: false
  jsonData:
    graphiteVersion: "1.1"
    tlsAuth: false
    tlsAuthWithCACert: false
  version: 1
  editable: false
