import logging
import datetime as dt

import pandas as pd

from run import Symbol, Ticker


logger = logging.getLogger()


def gen_ways(symbols: list[Symbol], max_depth: int = 5) -> list[str]:
    """Generates all possible tokens exchange ways"""
    date_start = dt.datetime.utcnow()
    # generate ways
    ways = []
    def step(prev_token: str, passed_tokens: list) -> None:
        ways.append(passed_tokens)
        if len(passed_tokens) == max_depth:
            return
        for symbol in symbols:
            next_token = None
            if symbol.base_coin == prev_token and symbol.quote_coin not in passed_tokens:
                next_token = symbol.quote_coin
            if symbol.quote_coin == prev_token and symbol.base_coin not in passed_tokens:
                next_token = symbol.base_coin
            if not next_token:
                continue
            passed = passed_tokens + [next_token]
            step(prev_token=next_token, passed_tokens=passed)
    step(prev_token='USDT', passed_tokens=['USDT'])
    date_end = dt.datetime.utcnow()
    logger.info('calculation time: %s', date_end - date_start)
    # close ways with USDT
    to_usdt_map = [
        symbol.quote_coin if symbol.base_coin == 'USDT' else symbol.base_coin
        for symbol in symbols
        if symbol.base_coin == 'USDT' or symbol.quote_coin == 'USDT'
    ]
    for way in ways:
        if way[-1] in to_usdt_map:
            way.append('USDT')
    return ways


def test_gen_ways() -> None:
    symbols = [
        Symbol(alias='USDTUSDC', base_coin='USDT', quote_coin='USDC'),
        Symbol(alias='MNTUSDC', base_coin='MNT', quote_coin='USDC'),
        Symbol(alias='BTCMNT', base_coin='BTC', quote_coin='MNT'),
        Symbol(alias='BTCUSDT', base_coin='BTC', quote_coin='USDT'),
    ]
    ways = gen_ways(symbols=symbols)
    expected_ways = [
        ['USDT'],
        ['USDT', 'USDC', 'USDT'],
        ['USDT', 'USDC', 'MNT'],
        ['USDT', 'USDC', 'MNT', 'BTC', 'USDT'],
        ['USDT', 'BTC', 'USDT'],
        ['USDT', 'BTC', 'MNT'],
        ['USDT', 'BTC', 'MNT', 'USDC', 'USDT'],
    ]
    assert ways == expected_ways


def test_gen_ways_2() -> None:
    symbols = [
        Symbol(alias='USDTUSDC', base_coin='USDT', quote_coin='USDC'),
        Symbol(alias='MNTUSDC', base_coin='MNT', quote_coin='USDC'),
        Symbol(alias='BTCMNT', base_coin='BTC', quote_coin='MNT'),
        Symbol(alias='BTCUSDT', base_coin='BTC', quote_coin='USDT'),
    ]
    ways = gen_ways(symbols=symbols, max_depth=3)
    expected_ways = [
        ['USDT'],
        ['USDT', 'USDC', 'USDT'],
        ['USDT', 'USDC', 'MNT'],
        ['USDT', 'BTC', 'USDT'],
        ['USDT', 'BTC', 'MNT'],
    ]
    assert ways == expected_ways


def gen_prices(symbols: list[Symbol], tickers: list[Ticker]) -> dict[str, float]:
    symbols_map = {symbol.alias: symbol for symbol in symbols}
    prices = {}
    for ticker in tickers:
        alias = ticker.symbol_alias
        if not (symbol := symbols_map.get(alias)):
            logger.warning('alias %s doesnt exists', alias)
            continue
        key_base_quote = '{}{}'.format(symbol.base_coin, symbol.quote_coin)
        key_quote_base = '{}{}'.format(symbol.quote_coin, symbol.base_coin)
        prices[key_base_quote] = ticker.last_price
        prices[key_quote_base] = 1 / ticker.last_price
    return prices


def test_gen_prices() -> None:
    symbols = [Symbol(alias='ETHUSDT', base_coin='ETH', quote_coin='USDT')]
    tickers = [Ticker(symbol_alias='ETHUSDT', last_price=1954.12)]
    prices = gen_prices(symbols=symbols, tickers=tickers)
    assert prices == {'ETHUSDT': 1954.12, 'USDTETH': 0.0005117392995312468}


def main() -> None:
    logging.basicConfig(level=logging.INFO)

    symbols = [
        Symbol(alias='BTCUSDT', base_coin='BTC', quote_coin='USDT'),
        Symbol(alias='ETHUSDT', base_coin='ETH', quote_coin='USDT'),
        Symbol(alias='XRPUSDT', base_coin='XRP', quote_coin='USDT'),
        Symbol(alias='EOSUSDT', base_coin='EOS', quote_coin='USDT'),
        Symbol(alias='ETHBTC', base_coin='ETH', quote_coin='BTC'),
        Symbol(alias='XRPBTC', base_coin='XRP', quote_coin='BTC'),
        Symbol(alias='DOTUSDT', base_coin='DOT', quote_coin='USDT'),
        Symbol(alias='XLMUSDT', base_coin='XLM', quote_coin='USDT'),
        Symbol(alias='LTCUSDT', base_coin='LTC', quote_coin='USDT'),
        Symbol(alias='DOGEUSDT', base_coin='DOGE', quote_coin='USDT'),
        Symbol(alias='CHZUSDT', base_coin='CHZ', quote_coin='USDT'),
        Symbol(alias='AXSUSDT', base_coin='AXS', quote_coin='USDT'),
        Symbol(alias='MANAUSDT', base_coin='MANA', quote_coin='USDT'),
        Symbol(alias='DYDXUSDT', base_coin='DYDX', quote_coin='USDT'),
        Symbol(alias='MKRUSDT', base_coin='MKR', quote_coin='USDT'),
        Symbol(alias='COMPUSDT', base_coin='COMP', quote_coin='USDT'),
        Symbol(alias='AAVEUSDT', base_coin='AAVE', quote_coin='USDT'),
        Symbol(alias='YFIUSDT', base_coin='YFI', quote_coin='USDT'),
        Symbol(alias='LINKUSDT', base_coin='LINK', quote_coin='USDT'),
        Symbol(alias='SUSHIUSDT', base_coin='SUSHI', quote_coin='USDT'),
        Symbol(alias='UNIUSDT', base_coin='UNI', quote_coin='USDT'),
        Symbol(alias='KSMUSDT', base_coin='KSM', quote_coin='USDT'),
        Symbol(alias='ICPUSDT', base_coin='ICP', quote_coin='USDT'),
        Symbol(alias='ADAUSDT', base_coin='ADA', quote_coin='USDT'),
        Symbol(alias='ETCUSDT', base_coin='ETC', quote_coin='USDT'),
        Symbol(alias='KLAYUSDT', base_coin='KLAY', quote_coin='USDT'),
        Symbol(alias='XTZUSDT', base_coin='XTZ', quote_coin='USDT'),
        Symbol(alias='BCHUSDT', base_coin='BCH', quote_coin='USDT'),
        Symbol(alias='SRMUSDT', base_coin='SRM', quote_coin='USDT'),
        Symbol(alias='QNTUSDT', base_coin='QNT', quote_coin='USDT'),
        Symbol(alias='USDCUSDT', base_coin='USDC', quote_coin='USDT'),
        Symbol(alias='GRTUSDT', base_coin='GRT', quote_coin='USDT'),
        Symbol(alias='SOLUSDT', base_coin='SOL', quote_coin='USDT'),
        Symbol(alias='FILUSDT', base_coin='FIL', quote_coin='USDT'),
        Symbol(alias='OMGUSDT', base_coin='OMG', quote_coin='USDT'),
        Symbol(alias='TRIBEUSDT', base_coin='TRIBE', quote_coin='USDT'),
        Symbol(alias='BATUSDT', base_coin='BAT', quote_coin='USDT'),
        Symbol(alias='ZRXUSDT', base_coin='ZRX', quote_coin='USDT'),
        Symbol(alias='CRVUSDT', base_coin='CRV', quote_coin='USDT'),
        Symbol(alias='AGLDUSDT', base_coin='AGLD', quote_coin='USDT'),
        Symbol(alias='ANKRUSDT', base_coin='ANKR', quote_coin='USDT'),
        Symbol(alias='PERPUSDT', base_coin='PERP', quote_coin='USDT'),
        Symbol(alias='MATICUSDT', base_coin='MATIC', quote_coin='USDT'),
        Symbol(alias='WAVESUSDT', base_coin='WAVES', quote_coin='USDT'),
        Symbol(alias='LUNCUSDT', base_coin='LUNC', quote_coin='USDT'),
        Symbol(alias='SPELLUSDT', base_coin='SPELL', quote_coin='USDT'),
        Symbol(alias='SHIBUSDT', base_coin='SHIB', quote_coin='USDT'),
        Symbol(alias='FTMUSDT', base_coin='FTM', quote_coin='USDT'),
        Symbol(alias='ATOMUSDT', base_coin='ATOM', quote_coin='USDT'),
        Symbol(alias='ALGOUSDT', base_coin='ALGO', quote_coin='USDT'),
        Symbol(alias='ENJUSDT', base_coin='ENJ', quote_coin='USDT'),
        Symbol(alias='CBXUSDT', base_coin='CBX', quote_coin='USDT'),
        Symbol(alias='SANDUSDT', base_coin='SAND', quote_coin='USDT'),
        Symbol(alias='AVAXUSDT', base_coin='AVAX', quote_coin='USDT'),
        Symbol(alias='WOOUSDT', base_coin='WOO', quote_coin='USDT'),
        Symbol(alias='FTTUSDT', base_coin='FTT', quote_coin='USDT'),
        Symbol(alias='GODSUSDT', base_coin='GODS', quote_coin='USDT'),
        Symbol(alias='IMXUSDT', base_coin='IMX', quote_coin='USDT'),
        Symbol(alias='ENSUSDT', base_coin='ENS', quote_coin='USDT'),
        Symbol(alias='GMUSDT', base_coin='GM', quote_coin='USDT'),
        Symbol(alias='CWARUSDT', base_coin='CWAR', quote_coin='USDT'),
        Symbol(alias='CAKEUSDT', base_coin='CAKE', quote_coin='USDT'),
        Symbol(alias='STETHUSDT', base_coin='STETH', quote_coin='USDT'),
        Symbol(alias='GALFTUSDT', base_coin='GALFT', quote_coin='USDT'),
        Symbol(alias='LFWUSDT', base_coin='LFW', quote_coin='USDT'),
        Symbol(alias='SLPUSDT', base_coin='SLP', quote_coin='USDT'),
        Symbol(alias='C98USDT', base_coin='C98', quote_coin='USDT'),
        Symbol(alias='PSPUSDT', base_coin='PSP', quote_coin='USDT'),
        Symbol(alias='GENEUSDT', base_coin='GENE', quote_coin='USDT'),
        Symbol(alias='AVAUSDT', base_coin='AVA', quote_coin='USDT'),
        Symbol(alias='ONEUSDT', base_coin='ONE', quote_coin='USDT'),
        Symbol(alias='PTUUSDT', base_coin='PTU', quote_coin='USDT'),
        Symbol(alias='SHILLUSDT', base_coin='SHILL', quote_coin='USDT'),
        Symbol(alias='XYMUSDT', base_coin='XYM', quote_coin='USDT'),
        Symbol(alias='BOBAUSDT', base_coin='BOBA', quote_coin='USDT'),
        Symbol(alias='INSURUSDT', base_coin='INSUR', quote_coin='USDT'),
        Symbol(alias='JASMYUSDT', base_coin='JASMY', quote_coin='USDT'),
        Symbol(alias='GALAUSDT', base_coin='GALA', quote_coin='USDT'),
        Symbol(alias='RNDRUSDT', base_coin='RNDR', quote_coin='USDT'),
        Symbol(alias='TRVLUSDT', base_coin='TRVL', quote_coin='USDT'),
        Symbol(alias='WEMIXUSDT', base_coin='WEMIX', quote_coin='USDT'),
        Symbol(alias='XEMUSDT', base_coin='XEM', quote_coin='USDT'),
        Symbol(alias='BICOUSDT', base_coin='BICO', quote_coin='USDT'),
        Symbol(alias='CELUSDT', base_coin='CEL', quote_coin='USDT'),
        Symbol(alias='UMAUSDT', base_coin='UMA', quote_coin='USDT'),
        Symbol(alias='HOTUSDT', base_coin='HOT', quote_coin='USDT'),
        Symbol(alias='NEXOUSDT', base_coin='NEXO', quote_coin='USDT'),
        Symbol(alias='BNTUSDT', base_coin='BNT', quote_coin='USDT'),
        Symbol(alias='SNXUSDT', base_coin='SNX', quote_coin='USDT'),
        Symbol(alias='RENUSDT', base_coin='REN', quote_coin='USDT'),
        Symbol(alias='1INCHUSDT', base_coin='1INCH', quote_coin='USDT'),
        Symbol(alias='TELUSDT', base_coin='TEL', quote_coin='USDT'),
        Symbol(alias='SISUSDT', base_coin='SIS', quote_coin='USDT'),
        Symbol(alias='LRCUSDT', base_coin='LRC', quote_coin='USDT'),
        Symbol(alias='LDOUSDT', base_coin='LDO', quote_coin='USDT'),
        Symbol(alias='REALUSDT', base_coin='REAL', quote_coin='USDT'),
        Symbol(alias='KRLUSDT', base_coin='KRL', quote_coin='USDT'),
        Symbol(alias='DEVTUSDT', base_coin='DEVT', quote_coin='USDT'),
        Symbol(alias='CRAFTUSDT', base_coin='CRAFT', quote_coin='USDT'),
        Symbol(alias='ETHUSDC', base_coin='ETH', quote_coin='USDC'),
        Symbol(alias='BTCUSDC', base_coin='BTC', quote_coin='USDC'),
        Symbol(alias='1SOLUSDT', base_coin='1SOL', quote_coin='USDT'),
        Symbol(alias='PLTUSDT', base_coin='PLT', quote_coin='USDT'),
        Symbol(alias='IZIUSDT', base_coin='IZI', quote_coin='USDT'),
        Symbol(alias='QTUMUSDT', base_coin='QTUM', quote_coin='USDT'),
        Symbol(alias='DCRUSDT', base_coin='DCR', quote_coin='USDT'),
        Symbol(alias='ZENUSDT', base_coin='ZEN', quote_coin='USDT'),
        Symbol(alias='THETAUSDT', base_coin='THETA', quote_coin='USDT'),
        Symbol(alias='MXUSDT', base_coin='MX', quote_coin='USDT'),
        Symbol(alias='DGBUSDT', base_coin='DGB', quote_coin='USDT'),
        Symbol(alias='RVNUSDT', base_coin='RVN', quote_coin='USDT'),
        Symbol(alias='EGLDUSDT', base_coin='EGLD', quote_coin='USDT'),
        Symbol(alias='RUNEUSDT', base_coin='RUNE', quote_coin='USDT'),
        Symbol(alias='XLMBTC', base_coin='XLM', quote_coin='BTC'),
        Symbol(alias='XLMUSDC', base_coin='XLM', quote_coin='USDC'),
        Symbol(alias='SOLUSDC', base_coin='SOL', quote_coin='USDC'),
        Symbol(alias='XRPUSDC', base_coin='XRP', quote_coin='USDC'),
        Symbol(alias='ALGOBTC', base_coin='ALGO', quote_coin='BTC'),
        Symbol(alias='SOLBTC', base_coin='SOL', quote_coin='BTC'),
        Symbol(alias='RAINUSDT', base_coin='RAIN', quote_coin='USDT'),
        Symbol(alias='XECUSDT', base_coin='XEC', quote_coin='USDT'),
        Symbol(alias='ICXUSDT', base_coin='ICX', quote_coin='USDT'),
        Symbol(alias='XDCUSDT', base_coin='XDC', quote_coin='USDT'),
        Symbol(alias='HNTUSDT', base_coin='HNT', quote_coin='USDT'),
        Symbol(alias='BTGUSDT', base_coin='BTG', quote_coin='USDT'),
        Symbol(alias='ZILUSDT', base_coin='ZIL', quote_coin='USDT'),
        Symbol(alias='HBARUSDT', base_coin='HBAR', quote_coin='USDT'),
        Symbol(alias='FLOWUSDT', base_coin='FLOW', quote_coin='USDT'),
        Symbol(alias='SOSUSDT', base_coin='SOS', quote_coin='USDT'),
        Symbol(alias='KASTAUSDT', base_coin='KASTA', quote_coin='USDT'),
        Symbol(alias='STXUSDT', base_coin='STX', quote_coin='USDT'),
        Symbol(alias='SIDUSUSDT', base_coin='SIDUS', quote_coin='USDT'),
        Symbol(alias='VPADUSDT', base_coin='VPAD', quote_coin='USDT'),
        Symbol(alias='GGMUSDT', base_coin='GGM', quote_coin='USDT'),
        Symbol(alias='LOOKSUSDT', base_coin='LOOKS', quote_coin='USDT'),
        Symbol(alias='MBSUSDT', base_coin='MBS', quote_coin='USDT'),
        Symbol(alias='DAIUSDT', base_coin='DAI', quote_coin='USDT'),
        Symbol(alias='BUSDUSDT', base_coin='BUSD', quote_coin='USDT'),
        Symbol(alias='ACAUSDT', base_coin='ACA', quote_coin='USDT'),
        Symbol(alias='MVUSDT', base_coin='MV', quote_coin='USDT'),
        Symbol(alias='MIXUSDT', base_coin='MIX', quote_coin='USDT'),
        Symbol(alias='LTCUSDC', base_coin='LTC', quote_coin='USDC'),
        Symbol(alias='MANABTC', base_coin='MANA', quote_coin='BTC'),
        Symbol(alias='MATICBTC', base_coin='MATIC', quote_coin='BTC'),
        Symbol(alias='LTCBTC', base_coin='LTC', quote_coin='BTC'),
        Symbol(alias='DOTBTC', base_coin='DOT', quote_coin='BTC'),
        Symbol(alias='SANDBTC', base_coin='SAND', quote_coin='BTC'),
        Symbol(alias='MANAUSDC', base_coin='MANA', quote_coin='USDC'),
        Symbol(alias='MATICUSDC', base_coin='MATIC', quote_coin='USDC'),
        Symbol(alias='SANDUSDC', base_coin='SAND', quote_coin='USDC'),
        Symbol(alias='DOTUSDC', base_coin='DOT', quote_coin='USDC'),
        Symbol(alias='LUNCUSDC', base_coin='LUNC', quote_coin='USDC'),
        Symbol(alias='RSS3USDT', base_coin='RSS3', quote_coin='USDT'),
        Symbol(alias='SYNRUSDT', base_coin='SYNR', quote_coin='USDT'),
        Symbol(alias='TAPUSDT', base_coin='TAP', quote_coin='USDT'),
        Symbol(alias='ERTHAUSDT', base_coin='ERTHA', quote_coin='USDT'),
        Symbol(alias='GMXUSDT', base_coin='GMX', quote_coin='USDT'),
        Symbol(alias='TUSDT', base_coin='T', quote_coin='USDT'),
        Symbol(alias='ACHUSDT', base_coin='ACH', quote_coin='USDT'),
        Symbol(alias='JSTUSDT', base_coin='JST', quote_coin='USDT'),
        Symbol(alias='SUNUSDT', base_coin='SUN', quote_coin='USDT'),
        Symbol(alias='BTTUSDT', base_coin='BTT', quote_coin='USDT'),
        Symbol(alias='TRXUSDT', base_coin='TRX', quote_coin='USDT'),
        Symbol(alias='NFTUSDT', base_coin='NFT', quote_coin='USDT'),
        Symbol(alias='POKTUSDT', base_coin='POKT', quote_coin='USDT'),
        Symbol(alias='SCRTUSDT', base_coin='SCRT', quote_coin='USDT'),
        Symbol(alias='PSTAKEUSDT', base_coin='PSTAKE', quote_coin='USDT'),
        Symbol(alias='SONUSDT', base_coin='SON', quote_coin='USDT'),
        Symbol(alias='HEROUSDT', base_coin='HERO', quote_coin='USDT'),
        Symbol(alias='DOMEUSDT', base_coin='DOME', quote_coin='USDT'),
        Symbol(alias='ZBCUSDT', base_coin='ZBC', quote_coin='USDT'),
        Symbol(alias='USTCUSDT', base_coin='USTC', quote_coin='USDT'),
        Symbol(alias='BNBUSDT', base_coin='BNB', quote_coin='USDT'),
        Symbol(alias='NEARUSDT', base_coin='NEAR', quote_coin='USDT'),
        Symbol(alias='PAXGUSDT', base_coin='PAXG', quote_coin='USDT'),
        Symbol(alias='SDUSDT', base_coin='SD', quote_coin='USDT'),
        Symbol(alias='APEUSDT', base_coin='APE', quote_coin='USDT'),
        Symbol(alias='BTC3SUSDT', base_coin='BTC3S', quote_coin='USDT'),
        Symbol(alias='BTC3LUSDT', base_coin='BTC3L', quote_coin='USDT'),
        Symbol(alias='FIDAUSDT', base_coin='FIDA', quote_coin='USDT'),
        Symbol(alias='MINAUSDT', base_coin='MINA', quote_coin='USDT'),
        Symbol(alias='SCUSDT', base_coin='SC', quote_coin='USDT'),
        Symbol(alias='RACAUSDT', base_coin='RACA', quote_coin='USDT'),
        Symbol(alias='IMEUSDT', base_coin='IME', quote_coin='USDT'),
        Symbol(alias='CAPSUSDT', base_coin='CAPS', quote_coin='USDT'),
        Symbol(alias='STGUSDT', base_coin='STG', quote_coin='USDT'),
        Symbol(alias='GLMRUSDT', base_coin='GLMR', quote_coin='USDT'),
        Symbol(alias='MOVRUSDT', base_coin='MOVR', quote_coin='USDT'),
        Symbol(alias='ZAMUSDT', base_coin='ZAM', quote_coin='USDT'),
        Symbol(alias='ETHDAI', base_coin='ETH', quote_coin='DAI'),
        Symbol(alias='BTCDAI', base_coin='BTC', quote_coin='DAI'),
        Symbol(alias='WBTCUSDT', base_coin='WBTC', quote_coin='USDT'),
        Symbol(alias='XAVAUSDT', base_coin='XAVA', quote_coin='USDT'),
        Symbol(alias='MELOSUSDT', base_coin='MELOS', quote_coin='USDT'),
        Symbol(alias='GMTUSDT', base_coin='GMT', quote_coin='USDT'),
        Symbol(alias='GSTUSDT', base_coin='GST', quote_coin='USDT'),
        Symbol(alias='CELOUSDT', base_coin='CELO', quote_coin='USDT'),
        Symbol(alias='SFUNDUSDT', base_coin='SFUND', quote_coin='USDT'),
        Symbol(alias='ELTUSDT', base_coin='ELT', quote_coin='USDT'),
        Symbol(alias='LGXUSDT', base_coin='LGX', quote_coin='USDT'),
        Symbol(alias='APEXUSDT', base_coin='APEX', quote_coin='USDT'),
        Symbol(alias='CTCUSDT', base_coin='CTC', quote_coin='USDT'),
        Symbol(alias='COTUSDT', base_coin='COT', quote_coin='USDT'),
        Symbol(alias='KMONUSDT', base_coin='KMON', quote_coin='USDT'),
        Symbol(alias='PLYUSDT', base_coin='PLY', quote_coin='USDT'),
        Symbol(alias='XWGUSDT', base_coin='XWG', quote_coin='USDT'),
        Symbol(alias='FITFIUSDT', base_coin='FITFI', quote_coin='USDT'),
        Symbol(alias='STRMUSDT', base_coin='STRM', quote_coin='USDT'),
        Symbol(alias='GALUSDT', base_coin='GAL', quote_coin='USDT'),
        Symbol(alias='ETH3SUSDT', base_coin='ETH3S', quote_coin='USDT'),
        Symbol(alias='ETH3LUSDT', base_coin='ETH3L', quote_coin='USDT'),
        Symbol(alias='KOKUSDT', base_coin='KOK', quote_coin='USDT'),
        Symbol(alias='FAMEUSDT', base_coin='FAME', quote_coin='USDT'),
        Symbol(alias='XRP3SUSDT', base_coin='XRP3S', quote_coin='USDT'),
        Symbol(alias='XRP3LUSDT', base_coin='XRP3L', quote_coin='USDT'),
        Symbol(alias='USDDUSDT', base_coin='USDD', quote_coin='USDT'),
        Symbol(alias='OPUSDT', base_coin='OP', quote_coin='USDT'),
        Symbol(alias='LUNAUSDT', base_coin='LUNA', quote_coin='USDT'),
        Symbol(alias='DFIUSDT', base_coin='DFI', quote_coin='USDT'),
        Symbol(alias='MOVEZUSDT', base_coin='MOVEZ', quote_coin='USDT'),
        Symbol(alias='THNUSDT', base_coin='THN', quote_coin='USDT'),
        Symbol(alias='DOT3SUSDT', base_coin='DOT3S', quote_coin='USDT'),
        Symbol(alias='DOT3LUSDT', base_coin='DOT3L', quote_coin='USDT'),
        Symbol(alias='VINUUSDT', base_coin='VINU', quote_coin='USDT'),
        Symbol(alias='BELUSDT', base_coin='BEL', quote_coin='USDT'),
        Symbol(alias='FORTUSDT', base_coin='FORT', quote_coin='USDT'),
        Symbol(alias='AVAX2SUSDT', base_coin='AVAX2S', quote_coin='USDT'),
        Symbol(alias='AVAX2LUSDT', base_coin='AVAX2L', quote_coin='USDT'),
        Symbol(alias='ADA2SUSDT', base_coin='ADA2S', quote_coin='USDT'),
        Symbol(alias='ADA2LUSDT', base_coin='ADA2L', quote_coin='USDT'),
        Symbol(alias='WLKNUSDT', base_coin='WLKN', quote_coin='USDT'),
        Symbol(alias='KONUSDT', base_coin='KON', quote_coin='USDT'),
        Symbol(alias='LTC2SUSDT', base_coin='LTC2S', quote_coin='USDT'),
        Symbol(alias='LTC2LUSDT', base_coin='LTC2L', quote_coin='USDT'),
        Symbol(alias='SAND2SUSDT', base_coin='SAND2S', quote_coin='USDT'),
        Symbol(alias='SAND2LUSDT', base_coin='SAND2L', quote_coin='USDT'),
        Symbol(alias='OBXUSDT', base_coin='OBX', quote_coin='USDT'),
        Symbol(alias='SEORUSDT', base_coin='SEOR', quote_coin='USDT'),
        Symbol(alias='MNZUSDT', base_coin='MNZ', quote_coin='USDT'),
        Symbol(alias='CULTUSDT', base_coin='CULT', quote_coin='USDT'),
        Symbol(alias='DOGEUSDC', base_coin='DOGE', quote_coin='USDC'),
        Symbol(alias='EOSUSDC', base_coin='EOS', quote_coin='USDC'),
        Symbol(alias='CUSDUSDT', base_coin='CUSD', quote_coin='USDT'),
        Symbol(alias='SLGUSDT', base_coin='SLG', quote_coin='USDT'),
        Symbol(alias='CMPUSDT', base_coin='CMP', quote_coin='USDT'),
        Symbol(alias='KUNCIUSDT', base_coin='KUNCI', quote_coin='USDT'),
        Symbol(alias='GSTSUSDT', base_coin='GSTS', quote_coin='USDT'),
        Symbol(alias='XETAUSDT', base_coin='XETA', quote_coin='USDT'),
        Symbol(alias='AZYUSDT', base_coin='AZY', quote_coin='USDT'),
        Symbol(alias='MMCUSDT', base_coin='MMC', quote_coin='USDT'),
        Symbol(alias='FLOKIUSDT', base_coin='FLOKI', quote_coin='USDT'),
        Symbol(alias='BABYDOGEUSDT', base_coin='BABYDOGE', quote_coin='USDT'),
        Symbol(alias='STATUSDT', base_coin='STAT', quote_coin='USDT'),
        Symbol(alias='SAITAMAUSDT', base_coin='SAITAMA', quote_coin='USDT'),
        Symbol(alias='MATIC2SUSDT', base_coin='MATIC2S', quote_coin='USDT'),
        Symbol(alias='MATIC2LUSDT', base_coin='MATIC2L', quote_coin='USDT'),
        Symbol(alias='ETC2SUSDT', base_coin='ETC2S', quote_coin='USDT'),
        Symbol(alias='ETC2LUSDT', base_coin='ETC2L', quote_coin='USDT'),
        Symbol(alias='DICEUSDT', base_coin='DICE', quote_coin='USDT'),
        Symbol(alias='WAXPUSDT', base_coin='WAXP', quote_coin='USDT'),
        Symbol(alias='ARUSDT', base_coin='AR', quote_coin='USDT'),
        Symbol(alias='KDAUSDT', base_coin='KDA', quote_coin='USDT'),
        Symbol(alias='ROSEUSDT', base_coin='ROSE', quote_coin='USDT'),
        Symbol(alias='SLGUSDC', base_coin='SLG', quote_coin='USDC'),
        Symbol(alias='APE2SUSDT', base_coin='APE2S', quote_coin='USDT'),
        Symbol(alias='APE2LUSDT', base_coin='APE2L', quote_coin='USDT'),
        Symbol(alias='GMT2SUSDT', base_coin='GMT2S', quote_coin='USDT'),
        Symbol(alias='GMT2LUSDT', base_coin='GMT2L', quote_coin='USDT'),
        Symbol(alias='DEFYUSDT', base_coin='DEFY', quote_coin='USDT'),
        Symbol(alias='PSGUSDT', base_coin='PSG', quote_coin='USDT'),
        Symbol(alias='BARUSDT', base_coin='BAR', quote_coin='USDT'),
        Symbol(alias='JUVUSDT', base_coin='JUV', quote_coin='USDT'),
        Symbol(alias='ACMUSDT', base_coin='ACM', quote_coin='USDT'),
        Symbol(alias='INTERUSDT', base_coin='INTER', quote_coin='USDT'),
        Symbol(alias='AFCUSDT', base_coin='AFC', quote_coin='USDT'),
        Symbol(alias='CITYUSDT', base_coin='CITY', quote_coin='USDT'),
        Symbol(alias='LINK2LUSDT', base_coin='LINK2L', quote_coin='USDT'),
        Symbol(alias='LINK2SUSDT', base_coin='LINK2S', quote_coin='USDT'),
        Symbol(alias='FTM2LUSDT', base_coin='FTM2L', quote_coin='USDT'),
        Symbol(alias='FTM2SUSDT', base_coin='FTM2S', quote_coin='USDT'),
        Symbol(alias='SOLOUSDT', base_coin='SOLO', quote_coin='USDT'),
        Symbol(alias='WBTCBTC', base_coin='WBTC', quote_coin='BTC'),
        Symbol(alias='AVAXUSDC', base_coin='AVAX', quote_coin='USDC'),
        Symbol(alias='ADAUSDC', base_coin='ADA', quote_coin='USDC'),
        Symbol(alias='OPUSDC', base_coin='OP', quote_coin='USDC'),
        Symbol(alias='DOGE2SUSDT', base_coin='DOGE2S', quote_coin='USDT'),
        Symbol(alias='DOGE2LUSDT', base_coin='DOGE2L', quote_coin='USDT'),
        Symbol(alias='ATOM2SUSDT', base_coin='ATOM2S', quote_coin='USDT'),
        Symbol(alias='ATOM2LUSDT', base_coin='ATOM2L', quote_coin='USDT'),
        Symbol(alias='OKSEUSDT', base_coin='OKSE', quote_coin='USDT'),
        Symbol(alias='APEXUSDC', base_coin='APEX', quote_coin='USDC'),
        Symbol(alias='TRXUSDC', base_coin='TRX', quote_coin='USDC'),
        Symbol(alias='ICPUSDC', base_coin='ICP', quote_coin='USDC'),
        Symbol(alias='LINKUSDC', base_coin='LINK', quote_coin='USDC'),
        Symbol(alias='GMTUSDC', base_coin='GMT', quote_coin='USDC'),
        Symbol(alias='CHZUSDC', base_coin='CHZ', quote_coin='USDC'),
        Symbol(alias='SHIBUSDC', base_coin='SHIB', quote_coin='USDC'),
        Symbol(alias='LDOUSDC', base_coin='LDO', quote_coin='USDC'),
        Symbol(alias='APEUSDC', base_coin='APE', quote_coin='USDC'),
        Symbol(alias='FILUSDC', base_coin='FIL', quote_coin='USDC'),
        Symbol(alias='CHRPUSDT', base_coin='CHRP', quote_coin='USDT'),
        Symbol(alias='EOS2SUSDT', base_coin='EOS2S', quote_coin='USDT'),
        Symbol(alias='EOS2LUSDT', base_coin='EOS2L', quote_coin='USDT'),
        Symbol(alias='WWYUSDT', base_coin='WWY', quote_coin='USDT'),
        Symbol(alias='LINGUSDT', base_coin='LING', quote_coin='USDT'),
        Symbol(alias='SWEATUSDT', base_coin='SWEAT', quote_coin='USDT'),
        Symbol(alias='DLCUSDT', base_coin='DLC', quote_coin='USDT'),
        Symbol(alias='OKGUSDT', base_coin='OKG', quote_coin='USDT'),
        Symbol(alias='ETHWUSDT', base_coin='ETHW', quote_coin='USDT'),
        Symbol(alias='INJUSDT', base_coin='INJ', quote_coin='USDT'),
        Symbol(alias='MPLXUSDT', base_coin='MPLX', quote_coin='USDT'),
        Symbol(alias='MIBRUSDT', base_coin='MIBR', quote_coin='USDT'),
        Symbol(alias='COUSDT', base_coin='CO', quote_coin='USDT'),
        Symbol(alias='AGLAUSDT', base_coin='AGLA', quote_coin='USDT'),
        Symbol(alias='RONDUSDT', base_coin='ROND', quote_coin='USDT'),
        Symbol(alias='QMALLUSDT', base_coin='QMALL', quote_coin='USDT'),
        Symbol(alias='PUMLXUSDT', base_coin='PUMLX', quote_coin='USDT'),
        Symbol(alias='GCAKEUSDT', base_coin='GCAKE', quote_coin='USDT'),
        Symbol(alias='APTUSDT', base_coin='APT', quote_coin='USDT'),
        Symbol(alias='APTUSDC', base_coin='APT', quote_coin='USDC'),
        Symbol(alias='USDTEUR', base_coin='USDT', quote_coin='EUR'),
        Symbol(alias='MTKUSDT', base_coin='MTK', quote_coin='USDT'),
        Symbol(alias='MCRTUSDT', base_coin='MCRT', quote_coin='USDT'),
        Symbol(alias='MASKUSDT', base_coin='MASK', quote_coin='USDT'),
        Symbol(alias='ECOXUSDT', base_coin='ECOX', quote_coin='USDT'),
        Symbol(alias='HFTUSDC', base_coin='HFT', quote_coin='USDC'),
        Symbol(alias='HFTUSDT', base_coin='HFT', quote_coin='USDT'),
        Symbol(alias='KCALUSDT', base_coin='KCAL', quote_coin='USDT'),
        Symbol(alias='PEOPLEUSDT', base_coin='PEOPLE', quote_coin='USDT'),
        Symbol(alias='TWTUSDT', base_coin='TWT', quote_coin='USDT'),
        Symbol(alias='ORTUSDT', base_coin='ORT', quote_coin='USDT'),
        Symbol(alias='HOOKUSDT', base_coin='HOOK', quote_coin='USDT'),
        Symbol(alias='PRIMALUSDT', base_coin='PRIMAL', quote_coin='USDT'),
        Symbol(alias='MCTUSDT', base_coin='MCT', quote_coin='USDT'),
        Symbol(alias='OASUSDT', base_coin='OAS', quote_coin='USDT'),
        Symbol(alias='MAGICUSDT', base_coin='MAGIC', quote_coin='USDT'),
        Symbol(alias='MEEUSDT', base_coin='MEE', quote_coin='USDT'),
        Symbol(alias='TONUSDT', base_coin='TON', quote_coin='USDT'),
        Symbol(alias='BONKUSDT', base_coin='BONK', quote_coin='USDT'),
        Symbol(alias='FLRUSDT', base_coin='FLR', quote_coin='USDT'),
        Symbol(alias='TIMEUSDT', base_coin='TIME', quote_coin='USDT'),
        Symbol(alias='3PUSDT', base_coin='3P', quote_coin='USDT'),
        Symbol(alias='RPLUSDT', base_coin='RPL', quote_coin='USDT'),
        Symbol(alias='SSVUSDT', base_coin='SSV', quote_coin='USDT'),
        Symbol(alias='FXSUSDT', base_coin='FXS', quote_coin='USDT'),
        Symbol(alias='COREUSDT', base_coin='CORE', quote_coin='USDT'),
        Symbol(alias='RDNTUSDT', base_coin='RDNT', quote_coin='USDT'),
        Symbol(alias='BLURUSDT', base_coin='BLUR', quote_coin='USDT'),
        Symbol(alias='LISUSDT', base_coin='LIS', quote_coin='USDT'),
        Symbol(alias='AGIXUSDT', base_coin='AGIX', quote_coin='USDT'),
        Symbol(alias='MDAOUSDT', base_coin='MDAO', quote_coin='USDT'),
        Symbol(alias='ACSUSDT', base_coin='ACS', quote_coin='USDT'),
        Symbol(alias='HVHUSDT', base_coin='HVH', quote_coin='USDT'),
        Symbol(alias='GNSUSDT', base_coin='GNS', quote_coin='USDT'),
        Symbol(alias='DPXUSDT', base_coin='DPX', quote_coin='USDT'),
        Symbol(alias='PIPUSDT', base_coin='PIP', quote_coin='USDT'),
        Symbol(alias='PRIMEUSDT', base_coin='PRIME', quote_coin='USDT'),
        Symbol(alias='EVERUSDT', base_coin='EVER', quote_coin='USDT'),
        Symbol(alias='VRAUSDT', base_coin='VRA', quote_coin='USDT'),
        Symbol(alias='GPTUSDT', base_coin='GPT', quote_coin='USDT'),
        Symbol(alias='FBUSDT', base_coin='FB', quote_coin='USDT'),
        Symbol(alias='DZOOUSDT', base_coin='DZOO', quote_coin='USDT'),
        Symbol(alias='IDUSDT', base_coin='ID', quote_coin='USDT'),
        Symbol(alias='ARBUSDC', base_coin='ARB', quote_coin='USDC'),
        Symbol(alias='ARBUSDT', base_coin='ARB', quote_coin='USDT'),
        Symbol(alias='XCADUSDT', base_coin='XCAD', quote_coin='USDT'),
        Symbol(alias='MBXUSDT', base_coin='MBX', quote_coin='USDT'),
        Symbol(alias='AXLUSDT', base_coin='AXL', quote_coin='USDT'),
        Symbol(alias='CGPTUSDT', base_coin='CGPT', quote_coin='USDT'),
        Symbol(alias='PLAYUSDT', base_coin='PLAY', quote_coin='USDT'),
        Symbol(alias='AGIUSDT', base_coin='AGI', quote_coin='USDT'),
        Symbol(alias='RLTMUSDT', base_coin='RLTM', quote_coin='USDT'),
        Symbol(alias='SUIUSDT', base_coin='SUI', quote_coin='USDT'),
        Symbol(alias='SUIUSDC', base_coin='SUI', quote_coin='USDC'),
        Symbol(alias='TAMAUSDT', base_coin='TAMA', quote_coin='USDT'),
        Symbol(alias='MVLUSDT', base_coin='MVL', quote_coin='USDT'),
        Symbol(alias='PEPEUSDT', base_coin='PEPE', quote_coin='USDT'),
        Symbol(alias='LADYSUSDT', base_coin='LADYS', quote_coin='USDT'),
        Symbol(alias='LMWRUSDT', base_coin='LMWR', quote_coin='USDT'),
        Symbol(alias='BOBUSDT', base_coin='BOB', quote_coin='USDT'),
        Symbol(alias='TOMIUSDT', base_coin='TOMI', quote_coin='USDT'),
        Symbol(alias='KARATEUSDT', base_coin='KARATE', quote_coin='USDT'),
        Symbol(alias='SUIAUSDT', base_coin='SUIA', quote_coin='USDT'),
        Symbol(alias='TURBOSUSDT', base_coin='TURBOS', quote_coin='USDT'),
        Symbol(alias='FMBUSDT', base_coin='FMB', quote_coin='USDT'),
        Symbol(alias='CAPOUSDT', base_coin='CAPO', quote_coin='USDT'),
        Symbol(alias='TENETUSDT', base_coin='TENET', quote_coin='USDT'),
        Symbol(alias='VELOUSDT', base_coin='VELO', quote_coin='USDT'),
        Symbol(alias='ELDAUSDT', base_coin='ELDA', quote_coin='USDT'),
        Symbol(alias='CANDYUSDT', base_coin='CANDY', quote_coin='USDT'),
        Symbol(alias='FONUSDT', base_coin='FON', quote_coin='USDT'),
        Symbol(alias='OMNUSDT', base_coin='OMN', quote_coin='USDT'),
        Symbol(alias='TOMSUSDT', base_coin='TOMS', quote_coin='USDT'),
        Symbol(alias='MTCUSDT', base_coin='MTC', quote_coin='USDT'),
        Symbol(alias='VELAUSDT', base_coin='VELA', quote_coin='USDT'),
        Symbol(alias='USDTBRZ', base_coin='USDT', quote_coin='BRZ'),
        Symbol(alias='BTCBRZ', base_coin='BTC', quote_coin='BRZ'),
        Symbol(alias='PENDLEUSDT', base_coin='PENDLE', quote_coin='USDT'),
        Symbol(alias='EGOUSDT', base_coin='EGO', quote_coin='USDT'),
        Symbol(alias='PEPE2USDT', base_coin='PEPE2', quote_coin='USDT'),
        Symbol(alias='NYMUSDT', base_coin='NYM', quote_coin='USDT'),
        Symbol(alias='MNTUSDT', base_coin='MNT', quote_coin='USDT'),
        Symbol(alias='MNTUSDC', base_coin='MNT', quote_coin='USDC'),
        Symbol(alias='MNTBTC', base_coin='MNT', quote_coin='BTC'),
        Symbol(alias='GSWIFTUSDT', base_coin='GSWIFT', quote_coin='USDT'),
        Symbol(alias='SALDUSDT', base_coin='SALD', quote_coin='USDT'),
        Symbol(alias='ARKMUSDT', base_coin='ARKM', quote_coin='USDT'),
        Symbol(alias='NEONUSDT', base_coin='NEON', quote_coin='USDT'),
        Symbol(alias='WLDUSDC', base_coin='WLD', quote_coin='USDC'),
        Symbol(alias='WLDUSDT', base_coin='WLD', quote_coin='USDT'),
        Symbol(alias='PLANETUSDT', base_coin='PLANET', quote_coin='USDT'),
        Symbol(alias='DSRUNUSDT', base_coin='DSRUN', quote_coin='USDT'),
        Symbol(alias='SPARTAUSDT', base_coin='SPARTA', quote_coin='USDT'),
        Symbol(alias='TAVAUSDT', base_coin='TAVA', quote_coin='USDT'),
    ]
    tickers = [
        Ticker(symbol_alias='LRCUSDT', last_price=0.2254),
        Ticker(symbol_alias='XYMUSDT', last_price=0.0273),
        Ticker(symbol_alias='ICXUSDT', last_price=0.2115),
        Ticker(symbol_alias='MNTBTC', last_price=1.572e-05),
        Ticker(symbol_alias='MATICBTC', last_price=2.328e-05),
        Ticker(symbol_alias='IZIUSDT', last_price=0.013607),
        Ticker(symbol_alias='AVAXUSDC', last_price=12.5302),
        Ticker(symbol_alias='USTCUSDT', last_price=0.01507),
        Ticker(symbol_alias='MVUSDT', last_price=0.03573),
        Ticker(symbol_alias='SFUNDUSDT', last_price=0.70698),
        Ticker(symbol_alias='LTC2SUSDT', last_price=0.4837),
        Ticker(symbol_alias='PIPUSDT', last_price=0.09139),
        Ticker(symbol_alias='LINK2LUSDT', last_price=4.7496),
        Ticker(symbol_alias='FLOWUSDT', last_price=0.561),
        Ticker(symbol_alias='TRXUSDC', last_price=0.07704),
        Ticker(symbol_alias='MOVRUSDT', last_price=5.141),
        Ticker(symbol_alias='BTCUSDC', last_price=29486.11),
        Ticker(symbol_alias='SLGUSDT', last_price=0.012168),
        Ticker(symbol_alias='RONDUSDT', last_price=0.002329),
        Ticker(symbol_alias='FONUSDT', last_price=0.5386),
        Ticker(symbol_alias='TOMSUSDT', last_price=0.001884),
        Ticker(symbol_alias='3PUSDT', last_price=5.12e-09),
        Ticker(symbol_alias='CWARUSDT', last_price=0.00803),
        Ticker(symbol_alias='FITFIUSDT', last_price=0.003238),
        Ticker(symbol_alias='COTUSDT', last_price=0.022916),
        Ticker(symbol_alias='ADAUSDT', last_price=0.2963),
        Ticker(symbol_alias='SDUSDT', last_price=0.752),
        Ticker(symbol_alias='TRVLUSDT', last_price=0.028812),
        Ticker(symbol_alias='QMALLUSDT', last_price=0.1246),
        Ticker(symbol_alias='FAMEUSDT', last_price=0.000782),
        Ticker(symbol_alias='MNTUSDC', last_price=0.4633),
        Ticker(symbol_alias='HFTUSDT', last_price=0.38),
        Ticker(symbol_alias='OKGUSDT', last_price=0.001681),
        Ticker(symbol_alias='AVAX2SUSDT', last_price=0.9917),
        Ticker(symbol_alias='JASMYUSDT', last_price=0.004027),
        Ticker(symbol_alias='HNTUSDT', last_price=1.9069),
        Ticker(symbol_alias='GNSUSDT', last_price=4.8572),
        Ticker(symbol_alias='FLOKIUSDT', last_price=2.2567e-05),
        Ticker(symbol_alias='BNTUSDT', last_price=0.5372),
        Ticker(symbol_alias='SOLBTC', last_price=0.000836),
        Ticker(symbol_alias='LGXUSDT', last_price=0.002257),
        Ticker(symbol_alias='STGUSDT', last_price=0.6127),
        Ticker(symbol_alias='DOTBTC', last_price=0.00016938),
        Ticker(symbol_alias='SAITAMAUSDT', last_price=0.0007103),
        Ticker(symbol_alias='OPUSDC', last_price=1.5988),
        Ticker(symbol_alias='FMBUSDT', last_price=0.0187),
        Ticker(symbol_alias='ACHUSDT', last_price=0.017186),
        Ticker(symbol_alias='AVAXUSDT', last_price=12.5429),
        Ticker(symbol_alias='TONUSDT', last_price=1.2756),
        Ticker(symbol_alias='SUIAUSDT', last_price=0.0649),
        Ticker(symbol_alias='PRIMALUSDT', last_price=0.001078),
        Ticker(symbol_alias='LINK2SUSDT', last_price=1.7814),
        Ticker(symbol_alias='APEUSDT', last_price=1.8646),
        Ticker(symbol_alias='CULTUSDT', last_price=2.477e-06),
        Ticker(symbol_alias='SWEATUSDT', last_price=0.007017),
        Ticker(symbol_alias='ZILUSDT', last_price=0.02001),
        Ticker(symbol_alias='LINGUSDT', last_price=0.002829),
        Ticker(symbol_alias='BOBAUSDT', last_price=0.1316),
        Ticker(symbol_alias='KUNCIUSDT', last_price=0.005951),
        Ticker(symbol_alias='LINKUSDT', last_price=7.5616),
        Ticker(symbol_alias='GMXUSDT', last_price=45.0425),
        Ticker(symbol_alias='GODSUSDT', last_price=0.16626),
        Ticker(symbol_alias='XLMUSDC', last_price=0.1403),
        Ticker(symbol_alias='TAMAUSDT', last_price=0.00866),
        Ticker(symbol_alias='BNBUSDT', last_price=240.925),
        Ticker(symbol_alias='ARUSDT', last_price=4.9435),
        Ticker(symbol_alias='MCTUSDT', last_price=0.02153),
        Ticker(symbol_alias='MIXUSDT', last_price=0.001619),
        Ticker(symbol_alias='ADAUSDC', last_price=0.2959),
        Ticker(symbol_alias='AAVEUSDT', last_price=66.3418),
        Ticker(symbol_alias='1SOLUSDT', last_price=0.002274),
        Ticker(symbol_alias='RACAUSDT', last_price=0.00011276),
        Ticker(symbol_alias='RVNUSDT', last_price=0.01793),
        Ticker(symbol_alias='CHZUSDC', last_price=0.0754),
        Ticker(symbol_alias='ETHDAI', last_price=1851.57),
        Ticker(symbol_alias='CAPOUSDT', last_price=0.001532),
        Ticker(symbol_alias='TIMEUSDT', last_price=16.66),
        Ticker(symbol_alias='NFTUSDT', last_price=3.256e-07),
        Ticker(symbol_alias='RSS3USDT', last_price=0.12027),
        Ticker(symbol_alias='BTTUSDT', last_price=4.661e-07),
        Ticker(symbol_alias='OASUSDT', last_price=0.054001),
        Ticker(symbol_alias='ZRXUSDT', last_price=0.213),
        Ticker(symbol_alias='JUVUSDT', last_price=2.375),
        Ticker(symbol_alias='LUNCUSDC', last_price=7.756e-05),
        Ticker(symbol_alias='SUIUSDT', last_price=0.6057),
        Ticker(symbol_alias='GLMRUSDT', last_price=0.235),
        Ticker(symbol_alias='TUSDT', last_price=0.02357),
        Ticker(symbol_alias='SLGUSDC', last_price=0.012033),
        Ticker(symbol_alias='SANDUSDT', last_price=0.40414),
        Ticker(symbol_alias='AGIXUSDT', last_price=0.2129),
        Ticker(symbol_alias='KMONUSDT', last_price=0.00796),
        Ticker(symbol_alias='XRPBTC', last_price=2.146e-05),
        Ticker(symbol_alias='MOVEZUSDT', last_price=0.00107),
        Ticker(symbol_alias='TWTUSDT', last_price=0.9119),
        Ticker(symbol_alias='ADA2SUSDT', last_price=4.0022),
        Ticker(symbol_alias='VELAUSDT', last_price=1.314),
        Ticker(symbol_alias='APEXUSDT', last_price=0.1616),
        Ticker(symbol_alias='FORTUSDT', last_price=0.1303),
        Ticker(symbol_alias='GRTUSDT', last_price=0.10716),
        Ticker(symbol_alias='ETHUSDT', last_price=1854.21),
        Ticker(symbol_alias='OMGUSDT', last_price=0.567),
        Ticker(symbol_alias='DOGEUSDT', last_price=0.07582),
        Ticker(symbol_alias='USDTEUR', last_price=0.9144),
        Ticker(symbol_alias='ORTUSDT', last_price=0.004207),
        Ticker(symbol_alias='FIDAUSDT', last_price=0.2109),
        Ticker(symbol_alias='DOGEUSDC', last_price=0.07575),
        Ticker(symbol_alias='POKTUSDT', last_price=0.02903),
        Ticker(symbol_alias='GPTUSDT', last_price=0.014471),
        Ticker(symbol_alias='CUSDUSDT', last_price=0.9978),
        Ticker(symbol_alias='LUNAUSDT', last_price=0.5616),
        Ticker(symbol_alias='LISUSDT', last_price=0.013026),
        Ticker(symbol_alias='FTMUSDT', last_price=0.24198),
        Ticker(symbol_alias='CITYUSDT', last_price=3.3497),
        Ticker(symbol_alias='ETHUSDC', last_price=1851.9),
        Ticker(symbol_alias='QNTUSDT', last_price=102.0),
        Ticker(symbol_alias='ETHWUSDT', last_price=1.682),
        Ticker(symbol_alias='SAND2LUSDT', last_price=0.5721),
        Ticker(symbol_alias='APE2SUSDT', last_price=6.4499),
        Ticker(symbol_alias='UMAUSDT', last_price=1.6221),
        Ticker(symbol_alias='XRPUSDT', last_price=0.6341),
        Ticker(symbol_alias='THETAUSDT', last_price=0.7464),
        Ticker(symbol_alias='BCHUSDT', last_price=229.4),
        Ticker(symbol_alias='MNTUSDT', last_price=0.4642),
        Ticker(symbol_alias='DICEUSDT', last_price=0.0144),
        Ticker(symbol_alias='AXSUSDT', last_price=6.0356),
        Ticker(symbol_alias='STATUSDT', last_price=0.0739),
        Ticker(symbol_alias='GSTUSDT', last_price=0.01219),
        Ticker(symbol_alias='COMPUSDT', last_price=55.5),
        Ticker(symbol_alias='SAND2SUSDT', last_price=3.3341),
        Ticker(symbol_alias='DCRUSDT', last_price=14.6894),
        Ticker(symbol_alias='BTCBRZ', last_price=145195.5),
        Ticker(symbol_alias='AFCUSDT', last_price=1.5903),
        Ticker(symbol_alias='FTM2SUSDT', last_price=0.8775),
        Ticker(symbol_alias='ALGOUSDT', last_price=0.11242),
        Ticker(symbol_alias='PTUUSDT', last_price=0.2349),
        Ticker(symbol_alias='SOLOUSDT', last_price=0.1287),
        Ticker(symbol_alias='KRLUSDT', last_price=0.2354),
        Ticker(symbol_alias='DYDXUSDT', last_price=2.167),
        Ticker(symbol_alias='XECUSDT', last_price=2.884e-05),
        Ticker(symbol_alias='SOLUSDC', last_price=24.67),
        Ticker(symbol_alias='BELUSDT', last_price=0.6566),
        Ticker(symbol_alias='SHIBUSDT', last_price=1.0099e-05),
        Ticker(symbol_alias='HOTUSDT', last_price=0.001286),
        Ticker(symbol_alias='AVAX2LUSDT', last_price=2.4815),
        Ticker(symbol_alias='MELOSUSDT', last_price=0.002293),
        Ticker(symbol_alias='GGMUSDT', last_price=0.002879),
        Ticker(symbol_alias='LFWUSDT', last_price=0.008682),
        Ticker(symbol_alias='MBXUSDT', last_price=0.833),
        Ticker(symbol_alias='MNZUSDT', last_price=0.0002321),
        Ticker(symbol_alias='IMEUSDT', last_price=7.301e-05),
        Ticker(symbol_alias='BARUSDT', last_price=2.7316),
        Ticker(symbol_alias='ETHBTC', last_price=0.062796),
        Ticker(symbol_alias='LINKUSDC', last_price=7.5498),
        Ticker(symbol_alias='SPARTAUSDT', last_price=0.608),
        Ticker(symbol_alias='THNUSDT', last_price=0.045052),
        Ticker(symbol_alias='MANABTC', last_price=1.262e-05),
        Ticker(symbol_alias='BOBUSDT', last_price=6.23e-06),
        Ticker(symbol_alias='FTTUSDT', last_price=1.1584),
        Ticker(symbol_alias='MTCUSDT', last_price=0.041),
        Ticker(symbol_alias='ICPUSDT', last_price=4.0461),
        Ticker(symbol_alias='INSURUSDT', last_price=0.04895),
        Ticker(symbol_alias='TAVAUSDT', last_price=0.06102),
        Ticker(symbol_alias='MATIC2SUSDT', last_price=1.5587),
        Ticker(symbol_alias='USDCUSDT', last_price=1.0012),
        Ticker(symbol_alias='ARBUSDC', last_price=1.161),
        Ticker(symbol_alias='RENUSDT', last_price=0.0584),
        Ticker(symbol_alias='CANDYUSDT', last_price=0.0918),
        Ticker(symbol_alias='XETAUSDT', last_price=0.01015),
        Ticker(symbol_alias='MATICUSDT', last_price=0.6877),
        Ticker(symbol_alias='PENDLEUSDT', last_price=0.702),
        Ticker(symbol_alias='BTCUSDT', last_price=29517.78),
        Ticker(symbol_alias='SSVUSDT', last_price=17.7214),
        Ticker(symbol_alias='ERTHAUSDT', last_price=0.001423),
        Ticker(symbol_alias='USDDUSDT', last_price=1.0002),
        Ticker(symbol_alias='GALAUSDT', last_price=0.02293),
        Ticker(symbol_alias='QTUMUSDT', last_price=2.6196),
        Ticker(symbol_alias='XRP3SUSDT', last_price=0.02068),
        Ticker(symbol_alias='AZYUSDT', last_price=0.00695),
        Ticker(symbol_alias='SHIBUSDC', last_price=1.00929e-05),
        Ticker(symbol_alias='PLTUSDT', last_price=0.05598),
        Ticker(symbol_alias='DZOOUSDT', last_price=0.002664),
        Ticker(symbol_alias='RUNEUSDT', last_price=1.1126),
        Ticker(symbol_alias='FXSUSDT', last_price=6.2083),
        Ticker(symbol_alias='HEROUSDT', last_price=0.002839),
        Ticker(symbol_alias='DASHUSDT', last_price=31.9),
        Ticker(symbol_alias='GALUSDT', last_price=1.1834),
        Ticker(symbol_alias='C98USDT', last_price=0.1591),
        Ticker(symbol_alias='STXUSDT', last_price=0.58672),
        Ticker(symbol_alias='XEMUSDT', last_price=0.02962),
        Ticker(symbol_alias='RNDRUSDT', last_price=1.6914),
        Ticker(symbol_alias='ACAUSDT', last_price=0.0604),
        Ticker(symbol_alias='ECOXUSDT', last_price=0.3369),
        Ticker(symbol_alias='DOTUSDT', last_price=5.01),
        Ticker(symbol_alias='PSTAKEUSDT', last_price=0.03435),
        Ticker(symbol_alias='ENSUSDT', last_price=9.143),
        Ticker(symbol_alias='LDOUSDC', last_price=1.845),
        Ticker(symbol_alias='PEPEUSDT', last_price=1.2482e-06),
        Ticker(symbol_alias='AGLDUSDT', last_price=0.6152),
        Ticker(symbol_alias='TELUSDT', last_price=0.001291),
        Ticker(symbol_alias='TRXUSDT', last_price=0.07716),
        Ticker(symbol_alias='ETH3LUSDT', last_price=1.2229),
        Ticker(symbol_alias='OBXUSDT', last_price=0.0002001),
        Ticker(symbol_alias='LOOKSUSDT', last_price=0.0544),
        Ticker(symbol_alias='XCADUSDT', last_price=1.3869),
        Ticker(symbol_alias='MANAUSDC', last_price=0.3703),
        Ticker(symbol_alias='OPUSDT', last_price=1.5996),
        Ticker(symbol_alias='EOS2LUSDT', last_price=1.4828),
        Ticker(symbol_alias='PUMLXUSDT', last_price=0.01523),
        Ticker(symbol_alias='SHILLUSDT', last_price=0.00987),
        Ticker(symbol_alias='SOLUSDT', last_price=24.7),
        Ticker(symbol_alias='COREUSDT', last_price=0.8947),
        Ticker(symbol_alias='XLMUSDT', last_price=0.14051),
        Ticker(symbol_alias='ETC2SUSDT', last_price=3.2035),
        Ticker(symbol_alias='SOSUSDT', last_price=4.7e-08),
        Ticker(symbol_alias='MMCUSDT', last_price=0.030227),
        Ticker(symbol_alias='TOMIUSDT', last_price=3.011),
        Ticker(symbol_alias='ETC2LUSDT', last_price=1.4572),
        Ticker(symbol_alias='BTC3SUSDT', last_price=3.3052),
        Ticker(symbol_alias='STRMUSDT', last_price=0.01376),
        Ticker(symbol_alias='INTERUSDT', last_price=2.0949),
        Ticker(symbol_alias='TURBOSUSDT', last_price=0.001547),
        Ticker(symbol_alias='CRVUSDT', last_price=0.6052),
        Ticker(symbol_alias='CGPTUSDT', last_price=0.0609),
        Ticker(symbol_alias='ZECUSDT', last_price=29.38),
        Ticker(symbol_alias='XRPUSDC', last_price=0.6331),
        Ticker(symbol_alias='VINUUSDT', last_price=1.002e-08),
        Ticker(symbol_alias='EOSUSDC', last_price=0.7166),
        Ticker(symbol_alias='APEXUSDC', last_price=0.1626),
        Ticker(symbol_alias='HFTUSDC', last_price=0.3805),
        Ticker(symbol_alias='SANDUSDC', last_price=0.40253),
        Ticker(symbol_alias='MIBRUSDT', last_price=0.3155),
        Ticker(symbol_alias='INJUSDT', last_price=7.755),
        Ticker(symbol_alias='HOOKUSDT', last_price=0.9621),
        Ticker(symbol_alias='CHRPUSDT', last_price=0.004049),
        Ticker(symbol_alias='GSTSUSDT', last_price=0.001379),
        Ticker(symbol_alias='PERPUSDT', last_price=0.5125),
        Ticker(symbol_alias='WEMIXUSDT', last_price=0.6171),
        Ticker(symbol_alias='ACMUSDT', last_price=2.2045),
        Ticker(symbol_alias='XLMBTC', last_price=4.7615e-06),
        Ticker(symbol_alias='MINAUSDT', last_price=0.4669),
        Ticker(symbol_alias='XAVAUSDT', last_price=0.19),
        Ticker(symbol_alias='MBSUSDT', last_price=0.014557),
        Ticker(symbol_alias='ELTUSDT', last_price=0.0001396),
        Ticker(symbol_alias='WLDUSDC', last_price=1.7071),
        Ticker(symbol_alias='PSPUSDT', last_price=0.026579),
        Ticker(symbol_alias='WWYUSDT', last_price=0.004812),
        Ticker(symbol_alias='HBARUSDT', last_price=0.05709),
        Ticker(symbol_alias='COUSDT', last_price=0.004992),
        Ticker(symbol_alias='MAGICUSDT', last_price=0.7576),
        Ticker(symbol_alias='DGBUSDT', last_price=0.008103),
        Ticker(symbol_alias='NEONUSDT', last_price=0.05821),
        Ticker(symbol_alias='VRAUSDT', last_price=0.004584),
        Ticker(symbol_alias='IDUSDT', last_price=0.26345),
        Ticker(symbol_alias='GALFTUSDT', last_price=2.37982),
        Ticker(symbol_alias='RAINUSDT', last_price=0.001111),
        Ticker(symbol_alias='SEORUSDT', last_price=0.001684),
        Ticker(symbol_alias='TENETUSDT', last_price=0.1117),
        Ticker(symbol_alias='BUSDUSDT', last_price=1.0011),
        Ticker(symbol_alias='1INCHUSDT', last_price=0.3104),
        Ticker(symbol_alias='MATICUSDC', last_price=0.6871),
        Ticker(symbol_alias='DEFYUSDT', last_price=0.004123),
        Ticker(symbol_alias='DOT3SUSDT', last_price=2.1481),
        Ticker(symbol_alias='EGLDUSDT', last_price=30.78),
        Ticker(symbol_alias='BTCDAI', last_price=29520.53),
        Ticker(symbol_alias='GCAKEUSDT', last_price=4.18e-07),
        Ticker(symbol_alias='APE2LUSDT', last_price=0.5292),
        Ticker(symbol_alias='ZENUSDT', last_price=8.6927),
        Ticker(symbol_alias='BONKUSDT', last_price=3.412e-07),
        Ticker(symbol_alias='MXUSDT', last_price=2.7787),
        Ticker(symbol_alias='XDCUSDT', last_price=0.06634),
        Ticker(symbol_alias='LUNCUSDT', last_price=7.764e-05),
        Ticker(symbol_alias='APTUSDT', last_price=7.1153),
        Ticker(symbol_alias='VPADUSDT', last_price=0.03453),
        Ticker(symbol_alias='ICPUSDC', last_price=4.0355),
        Ticker(symbol_alias='WOOUSDT', last_price=0.19126),
        Ticker(symbol_alias='NEARUSDT', last_price=1.3356),
        Ticker(symbol_alias='ETH3SUSDT', last_price=0.5402),
        Ticker(symbol_alias='DAIUSDT', last_price=1.0014),
        Ticker(symbol_alias='ALGOBTC', last_price=3.81e-06),
        Ticker(symbol_alias='DFIUSDT', last_price=0.2799),
        Ticker(symbol_alias='SALDUSDT', last_price=0.0482),
        Ticker(symbol_alias='CAPSUSDT', last_price=0.014625),
        Ticker(symbol_alias='RDNTUSDT', last_price=0.2824),
        Ticker(symbol_alias='DOMEUSDT', last_price=0.000998),
        Ticker(symbol_alias='GSWIFTUSDT', last_price=0.14163),
        Ticker(symbol_alias='BATUSDT', last_price=0.2225),
        Ticker(symbol_alias='DLCUSDT', last_price=0.08566),
        Ticker(symbol_alias='EOS2SUSDT', last_price=7.5916),
        Ticker(symbol_alias='SUSHIUSDT', last_price=0.714),
        Ticker(symbol_alias='TRIBEUSDT', last_price=0.28),
        Ticker(symbol_alias='XWGUSDT', last_price=0.0010944),
        Ticker(symbol_alias='GMTUSDT', last_price=0.2043),
        Ticker(symbol_alias='XRP3LUSDT', last_price=6.2931),
        Ticker(symbol_alias='KSMUSDT', last_price=22.6341),
        Ticker(symbol_alias='ENJUSDT', last_price=0.29078),
        Ticker(symbol_alias='WAVESUSDT', last_price=1.9258),
        Ticker(symbol_alias='ONEUSDT', last_price=0.01162),
        Ticker(symbol_alias='WBTCBTC', last_price=0.9975),
        Ticker(symbol_alias='MCRTUSDT', last_price=0.001605),
        Ticker(symbol_alias='AVAUSDT', last_price=0.5679),
        Ticker(symbol_alias='DOTUSDC', last_price=5.001),
        Ticker(symbol_alias='CELOUSDT', last_price=0.5165),
        Ticker(symbol_alias='EVERUSDT', last_price=0.06015),
        Ticker(symbol_alias='LMWRUSDT', last_price=0.0622),
        Ticker(symbol_alias='LADYSUSDT', last_price=2.7e-08),
        Ticker(symbol_alias='SCRTUSDT', last_price=0.3223),
        Ticker(symbol_alias='VELOUSDT', last_price=0.00246),
        Ticker(symbol_alias='NYMUSDT', last_price=0.1614),
        Ticker(symbol_alias='MATIC2LUSDT', last_price=3.2731),
        Ticker(symbol_alias='BTGUSDT', last_price=15.029),
        Ticker(symbol_alias='USDTBRZ', last_price=4.921),
        Ticker(symbol_alias='OKSEUSDT', last_price=0.01028),
        Ticker(symbol_alias='RLTMUSDT', last_price=0.01291),
        Ticker(symbol_alias='SNXUSDT', last_price=2.5642),
        Ticker(symbol_alias='WLDUSDT', last_price=1.7031),
        Ticker(symbol_alias='YFIUSDT', last_price=6347.46),
        Ticker(symbol_alias='PRIMEUSDT', last_price=2.629),
        Ticker(symbol_alias='KONUSDT', last_price=0.0209),
        Ticker(symbol_alias='ZBCUSDT', last_price=0.009416),
        Ticker(symbol_alias='GMT2SUSDT', last_price=4.8548),
        Ticker(symbol_alias='GMTUSDC', last_price=0.2041),
        Ticker(symbol_alias='RPLUSDT', last_price=27.9666),
        Ticker(symbol_alias='SPELLUSDT', last_price=0.00047101),
        Ticker(symbol_alias='LDOUSDT', last_price=1.8524),
        Ticker(symbol_alias='STETHUSDT', last_price=1855.39),
        Ticker(symbol_alias='MKRUSDT', last_price=1248.8),
        Ticker(symbol_alias='KASTAUSDT', last_price=0.01575),
        Ticker(symbol_alias='PLAYUSDT', last_price=0.07442),
        Ticker(symbol_alias='ANKRUSDT', last_price=0.02419),
        Ticker(symbol_alias='AXLUSDT', last_price=0.391),
        Ticker(symbol_alias='DOGE2SUSDT', last_price=0.4732),
        Ticker(symbol_alias='KARATEUSDT', last_price=0.0009978),
        Ticker(symbol_alias='XTZUSDT', last_price=0.7959),
        Ticker(symbol_alias='EGOUSDT', last_price=0.03166),
        Ticker(symbol_alias='LTCUSDC', last_price=83.43),
        Ticker(symbol_alias='CMPUSDT', last_price=0.01775),
        Ticker(symbol_alias='JSTUSDT', last_price=0.02262),
        Ticker(symbol_alias='ZAMUSDT', last_price=0.002628),
        Ticker(symbol_alias='MEEUSDT', last_price=0.003744),
        Ticker(symbol_alias='CHZUSDT', last_price=0.0753),
        Ticker(symbol_alias='UNIUSDT', last_price=6.1698),
        Ticker(symbol_alias='ACSUSDT', last_price=0.0022848),
        Ticker(symbol_alias='FILUSDC', last_price=4.136),
        Ticker(symbol_alias='DPXUSDT', last_price=85.0),
        Ticker(symbol_alias='FLRUSDT', last_price=0.01517),
        Ticker(symbol_alias='KCALUSDT', last_price=0.1355),
        Ticker(symbol_alias='NEXOUSDT', last_price=0.6428),
        Ticker(symbol_alias='DOT3LUSDT', last_price=0.5499),
        Ticker(symbol_alias='BTC3LUSDT', last_price=1.0684),
        Ticker(symbol_alias='SRMUSDT', last_price=0.0741),
        Ticker(symbol_alias='PAXGUSDT', last_price=1925.4193),
        Ticker(symbol_alias='DSRUNUSDT', last_price=0.05249),
        Ticker(symbol_alias='WAXPUSDT', last_price=0.04913),
        Ticker(symbol_alias='PEPE2USDT', last_price=1.665e-08),
        Ticker(symbol_alias='ARKMUSDT', last_price=0.41952),
        Ticker(symbol_alias='FBUSDT', last_price=1.078),
        Ticker(symbol_alias='AGIUSDT', last_price=0.05592),
        Ticker(symbol_alias='WLKNUSDT', last_price=0.008538),
        Ticker(symbol_alias='ATOM2SUSDT', last_price=4.1124),
        Ticker(symbol_alias='PLYUSDT', last_price=0.0001748),
        Ticker(symbol_alias='PSGUSDT', last_price=3.7022),
        Ticker(symbol_alias='APTUSDC', last_price=7.1103),
        Ticker(symbol_alias='MTKUSDT', last_price=0.00276),
        Ticker(symbol_alias='FILUSDT', last_price=4.138),
        Ticker(symbol_alias='GMUSDT', last_price=8.2774e-06),
        Ticker(symbol_alias='MPLXUSDT', last_price=0.0705),
        Ticker(symbol_alias='PEOPLEUSDT', last_price=0.01247),
        Ticker(symbol_alias='DOGE2LUSDT', last_price=4.4815),
        Ticker(symbol_alias='SCUSDT', last_price=0.003546),
        Ticker(symbol_alias='FTM2LUSDT', last_price=1.4558),
        Ticker(symbol_alias='GMT2LUSDT', last_price=0.122294),
        Ticker(symbol_alias='ARBUSDT', last_price=1.161),
        Ticker(symbol_alias='LTCUSDT', last_price=83.53),
        Ticker(symbol_alias='BLURUSDT', last_price=0.28779),
        Ticker(symbol_alias='ATOM2LUSDT', last_price=2.8387),
        Ticker(symbol_alias='KLAYUSDT', last_price=0.15687),
        Ticker(symbol_alias='WBTCUSDT', last_price=29403.64),
        Ticker(symbol_alias='SIDUSUSDT', last_price=0.0009255),
        Ticker(symbol_alias='MANAUSDT', last_price=0.3711),
        Ticker(symbol_alias='CTCUSDT', last_price=0.205483),
        Ticker(symbol_alias='ELDAUSDT', last_price=0.008059),
        Ticker(symbol_alias='LTC2LUSDT', last_price=19.5847),
        Ticker(symbol_alias='TAPUSDT', last_price=0.003234),
        Ticker(symbol_alias='HVHUSDT', last_price=0.0264),
        Ticker(symbol_alias='KOKUSDT', last_price=0.00789),
        Ticker(symbol_alias='BABYDOGEUSDT', last_price=1.187e-09),
        Ticker(symbol_alias='MVLUSDT', last_price=0.003608),
        Ticker(symbol_alias='CELUSDT', last_price=0.1553),
        Ticker(symbol_alias='SISUSDT', last_price=0.18963),
        Ticker(symbol_alias='SANDBTC', last_price=1.37e-05),
        Ticker(symbol_alias='KDAUSDT', last_price=0.5251),
        Ticker(symbol_alias='GENEUSDT', last_price=0.2659),
        Ticker(symbol_alias='IMXUSDT', last_price=0.71455),
        Ticker(symbol_alias='ROSEUSDT', last_price=0.0476),
        Ticker(symbol_alias='AGLAUSDT', last_price=0.02301),
        Ticker(symbol_alias='LTCBTC', last_price=0.002826),
        Ticker(symbol_alias='CAKEUSDT', last_price=1.4704),
        Ticker(symbol_alias='CBXUSDT', last_price=0.02167),
        Ticker(symbol_alias='OMNUSDT', last_price=0.00629),
        Ticker(symbol_alias='CRAFTUSDT', last_price=0.003),
        Ticker(symbol_alias='SUIUSDC', last_price=0.6047),
        Ticker(symbol_alias='BICOUSDT', last_price=0.25),
        Ticker(symbol_alias='ATOMUSDT', last_price=8.4086),
        Ticker(symbol_alias='DEVTUSDT', last_price=0.001309),
        Ticker(symbol_alias='SUNUSDT', last_price=0.00548),
        Ticker(symbol_alias='ETCUSDT', last_price=17.74),
        Ticker(symbol_alias='APEUSDC', last_price=1.8631),
        Ticker(symbol_alias='MASKUSDT', last_price=3.4646),
        Ticker(symbol_alias='EOSUSDT', last_price=0.7174),
        Ticker(symbol_alias='REALUSDT', last_price=0.04343),
        Ticker(symbol_alias='SLPUSDT', last_price=0.001662),
        Ticker(symbol_alias='SONUSDT', last_price=0.0001999),
        Ticker(symbol_alias='MDAOUSDT', last_price=0.1424),
        Ticker(symbol_alias='PLANETUSDT', last_price=6.217e-05),
        Ticker(symbol_alias='ADA2LUSDT', last_price=1.5755),
        Ticker(symbol_alias='SYNRUSDT', last_price=0.000781),
    ]
    prices = gen_prices(symbols=symbols, tickers=tickers)

    max_depth = 6
    columns=['step{}'.format(i+1) for i in range(max_depth+1)]
    ways = gen_ways(symbols=symbols, max_depth=max_depth)
    ways_for_df = [
        way
        for way in ways
        if len(way) > 3 and way[-1] == 'USDT'
    ]

    def apply_price(row: pd.Series) -> float:
        tokens = [x for x in row.tolist() if x]
        amount = 100  # at the beginning amoutn is USDT
        for i in range(len(tokens)-1):
            key = '{}{}'.format(tokens[i], tokens[i+1])
            amount *= prices[key]
        return amount

    ways_df = pd.DataFrame(ways_for_df, columns=columns).assign(
        final_price=lambda x: x.apply(apply_price, axis=1),
    )

    # USDT -> USDC -> MNT -> BTC -> USDT
    # ways_df[lambda x: x.step2 == 'USDC'][lambda x: x.step3 == 'MNT'][lambda x: x.step4 == 'BTC'][lambda x: x.step5 == 'USDT']
    # TODO: find USDT amount after circling 100USDT with fees
    # TODO: check real prices difference after a circle
    breakpoint()
    pass


if __name__ == '__main__':
    test_gen_ways()
    test_gen_ways_2()
    test_gen_prices()
    main()
